<Project>
  <PropertyGroup>
    <Version>0.4.0</Version>
    <AssemblyVersion>0.4.0.0</AssemblyVersion>
    <FileVersion>0.4.0.0</FileVersion>
    <InformationalVersion>0.4.0</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AuraIntermediateRoot Condition="'$(AuraIntermediateRoot)' == '' and '$(AURA_INTERMEDIATE_ROOT)' != ''">$(AURA_INTERMEDIATE_ROOT)</AuraIntermediateRoot>
    <AuraIntermediateRoot Condition="'$(AuraIntermediateRoot)' == '' and '$(CI)' == 'true'">$(MSBuildThisFileDirectory).verify_build\$(MSBuildProjectName)\$(Configuration)\</AuraIntermediateRoot>
    <BaseIntermediateOutputPath Condition="'$(AuraIntermediateRoot)' != ''">$(AuraIntermediateRoot)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath Condition="'$(AuraIntermediateRoot)' != ''">$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes Condition="'$(AuraIntermediateRoot)' != ''">$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup Condition="'$(AuraIntermediateRoot)' != ''">
    <Compile Remove="obj\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*" />
    <None Remove="obj\**\*" />
  </ItemGroup>
</Project>
