-- 寓瞳系统 PostgreSQL 基础表结构
-- 目标：PostgreSQL 16+，UTF-8

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS sys_role (
  role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(64) NOT NULL,
  permission_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(64) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id BIGINT NOT NULL REFERENCES sys_role(role_id),
  status SMALLINT NOT NULL DEFAULT 1,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nvr_device (
  device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  ip VARCHAR(64) NOT NULL,
  port INT NOT NULL,
  brand VARCHAR(32) NOT NULL,
  protocol VARCHAR(32) NOT NULL,
  hmac_secret VARCHAR(255) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'offline',
  last_seen_at TIMESTAMPTZ NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_roi (
  roi_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id BIGINT NOT NULL,
  room_node_id BIGINT NOT NULL,
  vertices_json JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_floor (
  floor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  scale_ratio NUMERIC(10,4) NOT NULL DEFAULT 1.0000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_camera (
  camera_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  channel_no INT NOT NULL,
  pos_x NUMERIC(12,4) NOT NULL DEFAULT 0,
  pos_y NUMERIC(12,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dict_campus (
  node_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NULL,
  level_type VARCHAR(32) NOT NULL,
  node_name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS capture_record (
  capture_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  channel_no INT NOT NULL,
  capture_time TIMESTAMP NOT NULL,
  image_path TEXT NULL,
  feature_id VARCHAR(128) NULL,
  metadata_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS track_event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vid VARCHAR(64) NOT NULL,
  camera_id BIGINT NOT NULL,
  roi_id BIGINT NOT NULL,
  event_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS judge_result (
  judge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vid VARCHAR(64) NOT NULL,
  room_id BIGINT NOT NULL,
  judge_type VARCHAR(32) NOT NULL,
  judge_date DATE NOT NULL,
  detail_json JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS virtual_person (
  v_id VARCHAR(64) PRIMARY KEY,
  first_seen TIMESTAMP NOT NULL,
  last_seen TIMESTAMP NOT NULL,
  device_id BIGINT NOT NULL,
  capture_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_record (
  alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_type VARCHAR(32) NOT NULL,
  vid VARCHAR(64) NULL,
  room_id BIGINT NULL,
  detail_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_operation (
  op_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_name VARCHAR(64) NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  action_detail TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_system (
  system_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level VARCHAR(16) NOT NULL,
  source VARCHAR(64) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_config (
  config_key VARCHAR(128) PRIMARY KEY,
  config_value TEXT NOT NULL DEFAULT '',
  updated_by VARCHAR(64) NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_workflow (
  workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES alert_record(alert_id) ON DELETE CASCADE,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  assignee VARCHAR(64) NULL,
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  escalation_level INT NOT NULL DEFAULT 0,
  handover_to VARCHAR(64) NULL,
  note TEXT NULL,
  closed_at TIMESTAMP NULL,
  updated_by VARCHAR(64) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS space_topology_edge (
  edge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_camera_id BIGINT NOT NULL,
  to_camera_id BIGINT NOT NULL,
  relation_type VARCHAR(32) NOT NULL DEFAULT 'walkable',
  weight NUMERIC(10,4) NOT NULL DEFAULT 1.0000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS space_heatmap_snapshot (
  snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor_id BIGINT NOT NULL,
  bucket_start TIMESTAMP NOT NULL,
  bucket_minutes INT NOT NULL DEFAULT 60,
  heat_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_schedule (
  schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type VARCHAR(32) NOT NULL,
  cron_expr VARCHAR(64) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  delivery_channel VARCHAR(32) NOT NULL DEFAULT 'system',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by VARCHAR(64) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_run (
  run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NULL REFERENCES report_schedule(schedule_id) ON DELETE SET NULL,
  report_type VARCHAR(32) NOT NULL,
  range_start DATE NOT NULL,
  range_end DATE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'generated',
  summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(64) NULL,
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_delivery (
  delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES report_run(run_id) ON DELETE CASCADE,
  role_name VARCHAR(64) NOT NULL,
  delivery_channel VARCHAR(32) NOT NULL DEFAULT 'system',
  status VARCHAR(32) NOT NULL DEFAULT 'delivered',
  delivered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_project (
  tenant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_code VARCHAR(64) NOT NULL UNIQUE,
  tenant_name VARCHAR(128) NOT NULL,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_role_scope (
  scope_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  role_name VARCHAR(64) NOT NULL,
  permission_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_provider_config (
  provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name VARCHAR(64) NOT NULL,
  provider_type VARCHAR(32) NOT NULL,
  endpoint_url TEXT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  traffic_weight INT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_ab_experiment (
  experiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experiment_name VARCHAR(128) NOT NULL,
  provider_a_id BIGINT NOT NULL REFERENCES ai_provider_config(provider_id),
  provider_b_id BIGINT NOT NULL REFERENCES ai_provider_config(provider_id),
  traffic_split INT NOT NULL DEFAULT 50,
  metric_name VARCHAR(64) NOT NULL DEFAULT 'recall_at_k',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============ 表级注释 & 字段注释 ============
-- 说明：仅补充 COMMENT，不影响业务逻辑/约束/索引/数据初始化

COMMENT ON TABLE sys_role IS '系统角色表';
COMMENT ON COLUMN sys_role.role_id IS '角色ID';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.permission_json IS '角色权限（JSONB）';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';

COMMENT ON TABLE sys_user IS '系统用户表';
COMMENT ON COLUMN sys_user.user_id IS '用户ID';
COMMENT ON COLUMN sys_user.user_name IS '用户名';
COMMENT ON COLUMN sys_user.display_name IS '显示名称（用于页面展示）';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.role_id IS '角色ID（外键：sys_role.role_id）';
COMMENT ON COLUMN sys_user.status IS '状态（1启用，其他为禁用）';
COMMENT ON COLUMN sys_user.must_change_password IS '是否必须下次登录修改密码';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';

COMMENT ON TABLE nvr_device IS 'NVR/摄像头设备表';
COMMENT ON COLUMN nvr_device.device_id IS '设备ID';
COMMENT ON COLUMN nvr_device.name IS '设备名称';
COMMENT ON COLUMN nvr_device.ip IS '设备IP';
COMMENT ON COLUMN nvr_device.port IS '设备端口';
COMMENT ON COLUMN nvr_device.brand IS '设备品牌';
COMMENT ON COLUMN nvr_device.protocol IS '设备协议（如 ONVIF/Hikvision 等）';
COMMENT ON COLUMN nvr_device.hmac_secret IS '设备 HMAC 密钥';
COMMENT ON COLUMN nvr_device.status IS '设备状态（例如 offline/online）';
COMMENT ON COLUMN nvr_device.created_at IS '创建时间';

COMMENT ON TABLE map_roi IS 'ROI（感兴趣区域）映射表';
COMMENT ON COLUMN map_roi.roi_id IS 'ROI ID';
COMMENT ON COLUMN map_roi.camera_id IS '所属摄像头ID';
COMMENT ON COLUMN map_roi.room_node_id IS '所属房间节点ID';
COMMENT ON COLUMN map_roi.vertices_json IS 'ROI 多边形顶点（JSONB）';
COMMENT ON COLUMN map_roi.created_at IS '创建时间';

COMMENT ON TABLE map_floor IS '楼层映射/配置表';
COMMENT ON COLUMN map_floor.floor_id IS '楼层ID';
COMMENT ON COLUMN map_floor.node_id IS '节点ID（对应 dict_campus 的层级节点）';
COMMENT ON COLUMN map_floor.file_path IS '楼层图文件路径';
COMMENT ON COLUMN map_floor.scale_ratio IS '楼层图缩放比例';
COMMENT ON COLUMN map_floor.created_at IS '创建时间';

COMMENT ON TABLE map_camera IS '摄像头与楼层/设备关系表';
COMMENT ON COLUMN map_camera.camera_id IS '摄像头ID';
COMMENT ON COLUMN map_camera.floor_id IS '楼层ID';
COMMENT ON COLUMN map_camera.device_id IS '设备ID（nvr_device.device_id）';
COMMENT ON COLUMN map_camera.channel_no IS '设备通道号';
COMMENT ON COLUMN map_camera.pos_x IS '摄像头在楼层图的 X 坐标';
COMMENT ON COLUMN map_camera.pos_y IS '摄像头在楼层图的 Y 坐标';
COMMENT ON COLUMN map_camera.created_at IS '创建时间';

COMMENT ON TABLE dict_campus IS '校园/楼栋/房间等层级字典表';
COMMENT ON COLUMN dict_campus.node_id IS '节点ID';
COMMENT ON COLUMN dict_campus.parent_id IS '父节点ID';
COMMENT ON COLUMN dict_campus.level_type IS '层级类型（如 campus/building/floor/room）';
COMMENT ON COLUMN dict_campus.node_name IS '节点名称';
COMMENT ON COLUMN dict_campus.created_at IS '创建时间';

COMMENT ON TABLE capture_record IS '抓拍记录表';
COMMENT ON COLUMN capture_record.capture_id IS '抓拍记录ID';
COMMENT ON COLUMN capture_record.device_id IS '设备ID';
COMMENT ON COLUMN capture_record.channel_no IS '通道号';
COMMENT ON COLUMN capture_record.capture_time IS '抓拍时间';
COMMENT ON COLUMN capture_record.image_path IS '抓拍图片路径（可空）';
COMMENT ON COLUMN capture_record.feature_id IS '特征ID/向量ID（可空）';
COMMENT ON COLUMN capture_record.metadata_json IS '抓拍元数据（JSONB，可空）';
COMMENT ON COLUMN capture_record.created_at IS '创建时间';

COMMENT ON TABLE track_event IS '目标/人员轨迹事件表';
COMMENT ON COLUMN track_event.event_id IS '轨迹事件ID';
COMMENT ON COLUMN track_event.vid IS '目标ID（通常对应特征向量ID）';
COMMENT ON COLUMN track_event.camera_id IS '摄像头ID';
COMMENT ON COLUMN track_event.roi_id IS 'ROI ID';
COMMENT ON COLUMN track_event.event_time IS '事件时间';
COMMENT ON COLUMN track_event.created_at IS '创建时间';

COMMENT ON TABLE judge_result IS '研判结果表';
COMMENT ON COLUMN judge_result.judge_id IS '研判结果ID';
COMMENT ON COLUMN judge_result.vid IS '目标ID（通常对应特征向量ID）';
COMMENT ON COLUMN judge_result.room_id IS '房间ID';
COMMENT ON COLUMN judge_result.judge_type IS '研判类型';
COMMENT ON COLUMN judge_result.judge_date IS '研判日期';
COMMENT ON COLUMN judge_result.detail_json IS '研判详情（JSONB，可空）';
COMMENT ON COLUMN judge_result.created_at IS '创建时间';

COMMENT ON TABLE virtual_person IS '虚拟人员/追踪聚合表';
COMMENT ON COLUMN virtual_person.v_id IS '虚拟人员ID';
COMMENT ON COLUMN virtual_person.first_seen IS '首次出现时间';
COMMENT ON COLUMN virtual_person.last_seen IS '最后出现时间';
COMMENT ON COLUMN virtual_person.device_id IS '设备ID';
COMMENT ON COLUMN virtual_person.capture_count IS '出现次数';
COMMENT ON COLUMN virtual_person.created_at IS '创建时间';

COMMENT ON TABLE alert_record IS '告警记录表';
COMMENT ON COLUMN alert_record.alert_id IS '告警ID';
COMMENT ON COLUMN alert_record.alert_type IS '告警类型';
COMMENT ON COLUMN alert_record.vid IS '目标ID（可空）';
COMMENT ON COLUMN alert_record.room_id IS '房间ID（可空）';
COMMENT ON COLUMN alert_record.detail_json IS '告警详情（JSONB，可空）';
COMMENT ON COLUMN alert_record.created_at IS '创建时间';

COMMENT ON TABLE log_operation IS '系统操作日志表';
COMMENT ON COLUMN log_operation.op_id IS '操作日志ID';
COMMENT ON COLUMN log_operation.operator_name IS '操作员用户名';
COMMENT ON COLUMN log_operation.action_type IS '动作类型';
COMMENT ON COLUMN log_operation.action_detail IS '动作详情';
COMMENT ON COLUMN log_operation.created_at IS '创建时间';

COMMENT ON TABLE log_system IS '系统运行日志表';
COMMENT ON COLUMN log_system.system_log_id IS '系统日志ID';
COMMENT ON COLUMN log_system.level IS '日志级别';
COMMENT ON COLUMN log_system.source IS '日志来源';
COMMENT ON COLUMN log_system.message IS '日志内容';
COMMENT ON COLUMN log_system.created_at IS '创建时间';

COMMENT ON TABLE sys_config IS '系统运行时配置表';
COMMENT ON COLUMN sys_config.config_key IS '配置键';
COMMENT ON COLUMN sys_config.config_value IS '配置值';
COMMENT ON COLUMN sys_config.updated_by IS '最后更新人';
COMMENT ON COLUMN sys_config.updated_at IS '最后更新时间';

CREATE INDEX IF NOT EXISTS idx_capture_time_desc
  ON capture_record(capture_time, capture_id);

CREATE INDEX IF NOT EXISTS idx_capture_device_channel_time_desc
  ON capture_record(device_id, channel_no, capture_time DESC, capture_id DESC);

CREATE INDEX IF NOT EXISTS idx_track_event_time_desc
  ON track_event(event_time DESC, event_id DESC);

CREATE INDEX IF NOT EXISTS idx_track_event_time_id_desc
  ON track_event(event_time DESC, event_id DESC);

CREATE INDEX IF NOT EXISTS idx_track_event_vid_desc
  ON track_event(vid, event_id);

CREATE INDEX IF NOT EXISTS idx_track_event_vid_time_desc
  ON track_event(vid, event_time DESC, event_id DESC);

CREATE INDEX IF NOT EXISTS idx_capture_device_time_image
  ON capture_record(device_id, capture_time DESC, capture_id DESC)
  WHERE image_path IS NOT NULL AND btrim(image_path) <> '';

CREATE INDEX IF NOT EXISTS idx_capture_feature_time_image
  ON capture_record(feature_id, capture_time DESC, capture_id DESC)
  WHERE feature_id IS NOT NULL AND image_path IS NOT NULL AND btrim(image_path) <> '';

CREATE INDEX IF NOT EXISTS idx_map_camera_device_id
  ON map_camera(device_id);

CREATE INDEX IF NOT EXISTS idx_judge_date_type_desc
  ON judge_result(judge_date, judge_type, judge_id);

CREATE INDEX IF NOT EXISTS idx_alert_id_desc
  ON alert_record(alert_id);

CREATE INDEX IF NOT EXISTS idx_alert_created_id_desc
  ON alert_record(created_at DESC, alert_id DESC);

CREATE INDEX IF NOT EXISTS idx_alert_type_trgm
  ON alert_record USING GIN (alert_type gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_alert_detail_text_trgm
  ON alert_record USING GIN ((
    COALESCE(
      CASE
        WHEN detail_json IS NULL THEN ''
        WHEN jsonb_typeof(detail_json) = 'string' THEN trim(both '"' from detail_json::text)
        ELSE CAST(detail_json AS TEXT)
      END,
      ''
    )
  ) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_system_id_desc
  ON log_system(system_log_id);

CREATE INDEX IF NOT EXISTS idx_log_operation_created_id_desc
  ON log_operation(created_at DESC, op_id DESC);

CREATE INDEX IF NOT EXISTS idx_log_system_created_id_desc
  ON log_system(created_at DESC, system_log_id DESC);

CREATE INDEX IF NOT EXISTS idx_log_operation_operator_name_trgm
  ON log_operation USING GIN (operator_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_operation_action_type_trgm
  ON log_operation USING GIN (action_type gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_operation_action_detail_trgm
  ON log_operation USING GIN (action_detail gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_system_level_trgm
  ON log_system USING GIN (level gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_system_source_trgm
  ON log_system USING GIN (source gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_log_system_message_trgm
  ON log_system USING GIN (message gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_alert_workflow_alert_updated
  ON alert_workflow(alert_id, updated_at DESC, workflow_id DESC);

CREATE INDEX IF NOT EXISTS idx_alert_workflow_status_updated
  ON alert_workflow(status, updated_at DESC, workflow_id DESC);

CREATE INDEX IF NOT EXISTS idx_space_topology_from_camera
  ON space_topology_edge(from_camera_id, to_camera_id);

CREATE INDEX IF NOT EXISTS idx_space_heatmap_floor_bucket
  ON space_heatmap_snapshot(floor_id, bucket_start DESC, snapshot_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_schedule_type_enabled
  ON report_schedule(report_type, enabled, schedule_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_run_type_generated
  ON report_run(report_type, generated_at DESC, run_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_delivery_role_status
  ON report_delivery(role_name, status, delivered_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_role_scope
  ON tenant_role_scope(tenant_id, role_name);

CREATE INDEX IF NOT EXISTS idx_tenant_role_scope_role
  ON tenant_role_scope(role_name, tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_provider_enabled_weight
  ON ai_provider_config(enabled, traffic_weight DESC, provider_id DESC);

INSERT INTO sys_role (role_id, role_name, permission_json)
VALUES
  (1, 'super_admin', '["all"]'::jsonb),
  (2, 'building_admin', '["device","roi","track","alert","alert.manage","stats","device.diag","export","report.manage","space.manage","tenant.manage","ai.platform","media.analysis.view","media.analysis.manage","media.analysis.operate","graph.view"]'::jsonb)
ON CONFLICT (role_id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('sys_role', 'role_id'),
  COALESCE((SELECT MAX(role_id) FROM sys_role), 0) + 1,
  false
);

SELECT setval(
  pg_get_serial_sequence('sys_user', 'user_id'),
  COALESCE((SELECT MAX(user_id) FROM sys_user), 0) + 1,
  false
);

-- ============ 通用媒体解析控制面、可靠事件、向量与图投影 ============

CREATE TABLE IF NOT EXISTS media_analysis_provider (
  provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_code VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  adapter_type VARCHAR(64) NOT NULL DEFAULT 'standard_http',
  base_url TEXT NOT NULL,
  auth_type VARCHAR(32) NOT NULL DEFAULT 'hmac',
  secret_ref VARCHAR(255) NULL,
  webhook_auth_type VARCHAR(32) NOT NULL DEFAULT 'hmac',
  webhook_secret_ref VARCHAR(255) NULL,
  capabilities_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  protocol_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  timeout_seconds INT NOT NULL DEFAULT 10 CHECK (timeout_seconds BETWEEN 1 AND 300),
  max_concurrency INT NOT NULL DEFAULT 16 CHECK (max_concurrency BETWEEN 1 AND 10000),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_analysis_provider_auth CHECK (auth_type IN ('none', 'hmac', 'bearer', 'oauth2_client', 'mtls')),
  CONSTRAINT ck_media_analysis_provider_webhook_auth CHECK (webhook_auth_type IN ('hmac'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_media_analysis_provider_scope_code ON media_analysis_provider(COALESCE(tenant_id, 0), provider_code);
CREATE INDEX IF NOT EXISTS idx_media_analysis_provider_enabled ON media_analysis_provider(enabled, tenant_id, provider_id);

CREATE TABLE IF NOT EXISTS media_analysis_pipeline (
  pipeline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  pipeline_code VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  model_name VARCHAR(128) NOT NULL DEFAULT '',
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  input_types_json JSONB NOT NULL DEFAULT '["image"]'::jsonb,
  output_types_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  embedding_dimension INT NULL CHECK (embedding_dimension IS NULL OR embedding_dimension BETWEEN 1 AND 65535),
  default_options_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_analysis_pipeline_version UNIQUE(provider_id, pipeline_code, model_version)
);
CREATE INDEX IF NOT EXISTS idx_media_analysis_pipeline_enabled ON media_analysis_pipeline(provider_id, enabled, pipeline_id);

CREATE TABLE IF NOT EXISTS media_source (
  source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  camera_id BIGINT NOT NULL REFERENCES map_camera(camera_id) ON DELETE CASCADE,
  source_code VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'rtsp' CHECK (source_type IN ('rtsp', 'http', 'https', 'file', 'object')),
  uri_template TEXT NOT NULL,
  credential_ref VARCHAR(255) NULL,
  stream_profile VARCHAR(32) NOT NULL DEFAULT 'sub',
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  config_version BIGINT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_source_tenant_code UNIQUE(tenant_id, source_code),
  CONSTRAINT ux_media_source_tenant_camera_profile UNIQUE(tenant_id, camera_id, stream_profile)
);
CREATE INDEX IF NOT EXISTS idx_media_source_camera_enabled ON media_source(camera_id, enabled, source_id);

CREATE TABLE IF NOT EXISTS media_analysis_subscription (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  source_id BIGINT NOT NULL REFERENCES media_source(source_id) ON DELETE CASCADE,
  pipeline_id BIGINT NOT NULL REFERENCES media_analysis_pipeline(pipeline_id),
  client_subscription_id VARCHAR(128) NOT NULL UNIQUE,
  external_subscription_id VARCHAR(255) NULL,
  desired_state VARCHAR(32) NOT NULL DEFAULT 'stopped' CHECK (desired_state IN ('stopped', 'running')),
  observed_state VARCHAR(32) NOT NULL DEFAULT 'unknown' CHECK (observed_state IN ('unknown', 'starting', 'running', 'degraded', 'stopping', 'stopped', 'failed')),
  desired_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  applied_config_hash VARCHAR(64) NULL,
  last_heartbeat_at TIMESTAMPTZ NULL,
  last_reconciled_at TIMESTAMPTZ NULL,
  retry_count INT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  next_retry_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_analysis_subscription_target UNIQUE(tenant_id, source_id, pipeline_id)
);
CREATE INDEX IF NOT EXISTS idx_media_analysis_subscription_reconcile ON media_analysis_subscription(desired_state, observed_state, next_retry_at, subscription_id);
CREATE INDEX IF NOT EXISTS idx_media_analysis_subscription_heartbeat ON media_analysis_subscription(observed_state, last_heartbeat_at) WHERE observed_state IN ('starting', 'running', 'degraded');

CREATE TABLE IF NOT EXISTS media_analysis_job (
  job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  pipeline_id BIGINT NOT NULL REFERENCES media_analysis_pipeline(pipeline_id),
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  external_job_id VARCHAR(255) NULL,
  media_type VARCHAR(32) NOT NULL CHECK (media_type IN ('image', 'video')),
  media_uri TEXT NULL,
  request_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'submitting', 'accepted', 'running', 'completed', 'rejected', 'cancelling', 'cancelled', 'failed', 'retry_wait')),
  progress NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  retry_count INT NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  next_retry_at TIMESTAMPTZ NULL,
  error_code VARCHAR(64) NULL,
  error_message TEXT NULL,
  submitted_at TIMESTAMPTZ NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_analysis_job_idempotency UNIQUE(provider_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_media_analysis_job_work ON media_analysis_job(status, next_retry_at, job_id);
CREATE INDEX IF NOT EXISTS idx_media_analysis_job_tenant_created ON media_analysis_job(tenant_id, created_at DESC, job_id DESC);

CREATE TABLE IF NOT EXISTS integration_webhook_nonce (
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  nonce VARCHAR(128) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(provider_id, nonce)
);
CREATE INDEX IF NOT EXISTS idx_integration_webhook_nonce_expiry ON integration_webhook_nonce(expires_at);

CREATE TABLE IF NOT EXISTS media_analysis_inbox (
  inbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id),
  event_id VARCHAR(128) NOT NULL,
  provider_event_id VARCHAR(255) NULL,
  subscription_id BIGINT NULL REFERENCES media_analysis_subscription(subscription_id) ON DELETE SET NULL,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  sequence_no BIGINT NULL,
  schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  event_type VARCHAR(64) NOT NULL,
  event_time TIMESTAMPTZ NOT NULL,
  produced_at TIMESTAMPTZ NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payload_json JSONB NOT NULL,
  payload_hash VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'processing', 'processed', 'retry_wait', 'dead_letter', 'unsupported')),
  attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ NULL,
  locked_by VARCHAR(128) NULL,
  lock_until TIMESTAMPTZ NULL,
  processed_at TIMESTAMPTZ NULL,
  last_error_code VARCHAR(64) NULL,
  last_error TEXT NULL,
  trace_id VARCHAR(64) NULL,
  CONSTRAINT ux_media_analysis_inbox_provider_event UNIQUE(provider_id, event_id)
);
CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_work ON media_analysis_inbox(status, next_attempt_at, lock_until, inbox_id);
CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_tenant_received ON media_analysis_inbox(tenant_id, received_at DESC, inbox_id DESC);
CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_subscription_sequence ON media_analysis_inbox(subscription_id, sequence_no) WHERE subscription_id IS NOT NULL AND sequence_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS media_analysis_event (
  analysis_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inbox_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_inbox(inbox_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id),
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  subscription_id BIGINT NULL REFERENCES media_analysis_subscription(subscription_id) ON DELETE SET NULL,
  event_type VARCHAR(64) NOT NULL,
  event_time TIMESTAMPTZ NOT NULL,
  track_id VARCHAR(255) NULL,
  entity_id VARCHAR(255) NULL,
  embedding_id VARCHAR(255) NULL,
  confidence NUMERIC(8,6) NULL CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
  late_event BOOLEAN NOT NULL DEFAULT FALSE,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_media_analysis_event_source_time ON media_analysis_event(tenant_id, source_id, event_time DESC, analysis_event_id DESC);
CREATE INDEX IF NOT EXISTS idx_media_analysis_event_type_time ON media_analysis_event(tenant_id, event_type, event_time DESC, analysis_event_id DESC);
CREATE INDEX IF NOT EXISTS idx_media_analysis_event_track_time ON media_analysis_event(tenant_id, track_id, event_time, analysis_event_id) WHERE track_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_media_analysis_event_entity_time ON media_analysis_event(tenant_id, entity_id, event_time DESC, analysis_event_id DESC) WHERE entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS integration_outbox (
  outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload_json JSONB NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'processed', 'retry_wait', 'dead_letter')),
  attempt_count INT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(128) NULL,
  lock_until TIMESTAMPTZ NULL,
  processed_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_work ON integration_outbox(status, available_at, lock_until, outbox_id);
CREATE INDEX IF NOT EXISTS idx_integration_outbox_aggregate ON integration_outbox(aggregate_type, aggregate_id, outbox_id DESC);

CREATE TABLE IF NOT EXISTS media_artifact (
  artifact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  analysis_event_id BIGINT NULL REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL,
  provider_uri TEXT NULL,
  archive_uri TEXT NULL,
  media_type VARCHAR(64) NOT NULL,
  content_type VARCHAR(128) NULL,
  size_bytes BIGINT NULL CHECK (size_bytes IS NULL OR size_bytes >= 0),
  sha256 VARCHAR(64) NULL,
  archive_status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (archive_status IN ('pending','archiving','retry_wait','archived','failed','dead_letter','not_required')),
  expires_at TIMESTAMPTZ NULL,
  attempt_count INT NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(256) NULL,
  lock_until TIMESTAMPTZ NULL,
  last_error VARCHAR(2000) NULL,
  archived_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_media_artifact_archive_work ON media_artifact(archive_status,next_attempt_at,lock_until,artifact_id);

CREATE TABLE IF NOT EXISTS embedding_model (
  model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE SET NULL,
  model_code VARCHAR(128) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  dimension INT NOT NULL DEFAULT 512 CHECK (dimension = 512),
  distance_metric VARCHAR(32) NOT NULL DEFAULT 'cosine' CHECK (distance_metric IN ('cosine')),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_embedding_model_code_version UNIQUE(model_code, model_version)
);

CREATE TABLE IF NOT EXISTS feature_embedding (
  embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  external_embedding_id VARCHAR(255) NULL,
  vid VARCHAR(128) NOT NULL,
  capture_id BIGINT NULL REFERENCES capture_record(capture_id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES embedding_model(model_id),
  feature vector(512) NOT NULL,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_feature_embedding_sample
  ON feature_embedding(tenant_id,model_id,vid,capture_id) NULLS NOT DISTINCT;
CREATE INDEX IF NOT EXISTS idx_feature_embedding_tenant_model_vid ON feature_embedding(tenant_id, model_id, vid, embedding_id DESC);
CREATE INDEX IF NOT EXISTS idx_feature_embedding_capture ON feature_embedding(capture_id) WHERE capture_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_feature_embedding_feature_hnsw ON feature_embedding USING hnsw (feature vector_cosine_ops);

ALTER TABLE space_topology_edge
  ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS valid_from TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS valid_to TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX IF NOT EXISTS ux_space_topology_edge_relation ON space_topology_edge(from_camera_id, to_camera_id, relation_type);
CREATE INDEX IF NOT EXISTS idx_space_topology_to_camera ON space_topology_edge(to_camera_id, from_camera_id) WHERE enabled = TRUE;

CREATE TABLE IF NOT EXISTS graph_projection_checkpoint (
  projection_name VARCHAR(128) PRIMARY KEY,
  last_outbox_id BIGINT NULL,
  last_projected_at TIMESTAMPTZ NULL,
  graph_version VARCHAR(64) NOT NULL DEFAULT '1',
  status VARCHAR(32) NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'running', 'degraded', 'failed', 'rebuilding')),
  last_error TEXT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS graph_projection_rebuild (
  rebuild_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projection_name VARCHAR(128) NOT NULL,
  requested_by VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
  processed_vertices BIGINT NOT NULL DEFAULT 0,
  processed_edges BIGINT NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Media-analysis business facts, operational heartbeats, and vector migration evidence.
ALTER TABLE media_analysis_subscription
  ADD COLUMN IF NOT EXISTS last_sequence_no BIGINT NULL,
  ADD COLUMN IF NOT EXISTS last_event_time TIMESTAMPTZ NULL;
ALTER TABLE capture_record
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS camera_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS embedding_id BIGINT NULL;
ALTER TABLE alert_record
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS model_code VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS model_version VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS confidence NUMERIC(8,6) NULL;
ALTER TABLE judge_result
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS model_code VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS model_version VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS confidence NUMERIC(8,6) NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_tenant') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_camera') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_camera
      FOREIGN KEY(camera_id) REFERENCES map_camera(camera_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_analysis_event') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_embedding') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_embedding
      FOREIGN KEY(embedding_id) REFERENCES feature_embedding(embedding_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_alert_record_tenant') THEN
    ALTER TABLE alert_record ADD CONSTRAINT fk_alert_record_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_alert_record_analysis_event') THEN
    ALTER TABLE alert_record ADD CONSTRAINT fk_alert_record_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_judge_result_tenant') THEN
    ALTER TABLE judge_result ADD CONSTRAINT fk_judge_result_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_judge_result_analysis_event') THEN
    ALTER TABLE judge_result ADD CONSTRAINT fk_judge_result_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_integration_outbox_aggregate_event ON integration_outbox(aggregate_type,aggregate_id,event_type);
CREATE UNIQUE INDEX IF NOT EXISTS ux_media_artifact_event_uri ON media_artifact(analysis_event_id,provider_uri);
CREATE UNIQUE INDEX IF NOT EXISTS ux_track_event_natural ON track_event(vid,camera_id,event_time);
CREATE UNIQUE INDEX IF NOT EXISTS ux_capture_record_analysis_event ON capture_record(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_alert_record_analysis_event ON alert_record(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_judge_result_analysis_event ON judge_result(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_capture_record_tenant_camera_time ON capture_record(tenant_id,camera_id,capture_time DESC);

CREATE TABLE IF NOT EXISTS media_detection_fact (
  detection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  camera_id BIGINT NULL REFERENCES map_camera(camera_id) ON DELETE SET NULL,
  provider_track_id VARCHAR(256) NULL,
  object_type VARCHAR(128) NOT NULL,
  bbox_json JSONB NULL,
  confidence NUMERIC(8,6) NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  event_time TIMESTAMPTZ NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_detection_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1)
);
CREATE INDEX IF NOT EXISTS idx_media_detection_tenant_source_time ON media_detection_fact(tenant_id,source_id,event_time DESC);

CREATE TABLE IF NOT EXISTS media_track_binding (
  track_binding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  provider_track_id VARCHAR(256) NOT NULL,
  aura_track_id VARCHAR(64) NOT NULL,
  entity_id VARCHAR(128) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  last_sequence_no BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_track_binding_status CHECK(status IN ('active','ended')),
  CONSTRAINT ux_media_track_provider_track UNIQUE(tenant_id,provider_id,source_id,provider_track_id)
);
CREATE INDEX IF NOT EXISTS idx_media_track_binding_aura ON media_track_binding(tenant_id,aura_track_id,last_seen DESC);

CREATE TABLE IF NOT EXISTS media_identity_candidate (
  candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  track_binding_id BIGINT NULL REFERENCES media_track_binding(track_binding_id) ON DELETE SET NULL,
  candidate_vid VARCHAR(64) NULL,
  embedding_id BIGINT NULL REFERENCES feature_embedding(embedding_id) ON DELETE SET NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  confidence NUMERIC(8,6) NULL,
  decision VARCHAR(32) NOT NULL DEFAULT 'pending',
  decision_reason VARCHAR(512) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_media_identity_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1),
  CONSTRAINT ck_media_identity_decision CHECK(decision IN ('pending','linked','rejected','review'))
);
CREATE INDEX IF NOT EXISTS idx_media_identity_candidate_review ON media_identity_candidate(tenant_id,decision,created_at DESC);

CREATE TABLE IF NOT EXISTS media_behavior_fact (
  behavior_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  behavior_type VARCHAR(128) NOT NULL,
  provider_track_id VARCHAR(256) NULL,
  entity_id VARCHAR(128) NULL,
  room_id BIGINT NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  confidence NUMERIC(8,6) NULL,
  event_time TIMESTAMPTZ NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_behavior_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1)
);
CREATE INDEX IF NOT EXISTS idx_media_behavior_tenant_type_time ON media_behavior_fact(tenant_id,behavior_type,event_time DESC);

CREATE TABLE IF NOT EXISTS background_worker_heartbeat (
  worker_name VARCHAR(128) NOT NULL,
  instance_id VARCHAR(256) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  last_success_at TIMESTAMPTZ NULL,
  last_error_at TIMESTAMPTZ NULL,
  last_error VARCHAR(2000) NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(worker_name,instance_id)
);
CREATE INDEX IF NOT EXISTS idx_background_worker_heartbeat_updated ON background_worker_heartbeat(worker_name,updated_at DESC);

CREATE TABLE IF NOT EXISTS vector_migration_checkpoint (
  migration_name VARCHAR(128) PRIMARY KEY,
  source_engine VARCHAR(64) NOT NULL,
  target_engine VARCHAR(64) NOT NULL,
  last_source_key VARCHAR(512) NULL,
  scanned_count BIGINT NOT NULL DEFAULT 0,
  migrated_count BIGINT NOT NULL DEFAULT 0,
  skipped_count BIGINT NOT NULL DEFAULT 0,
  failed_count BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'idle',
  last_error VARCHAR(2000) NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_migration_checkpoint_status CHECK(status IN ('idle','running','completed','failed','cancelled'))
);
CREATE TABLE IF NOT EXISTS vector_shadow_evaluation (
  evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES embedding_model(model_id) ON DELETE CASCADE,
  sample_count INT NOT NULL,
  top_k INT NOT NULL,
  recall_at_k NUMERIC(10,8) NULL,
  mrr NUMERIC(10,8) NULL,
  topk_overlap NUMERIC(10,8) NULL,
  empty_result_rate NUMERIC(10,8) NULL,
  pgvector_p95_ms NUMERIC(14,4) NULL,
  legacy_p95_ms NUMERIC(14,4) NULL,
  report_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_shadow_sample CHECK(sample_count > 0 AND top_k > 0)
);
CREATE INDEX IF NOT EXISTS idx_vector_shadow_evaluation_model_time ON vector_shadow_evaluation(tenant_id,model_id,created_at DESC);
CREATE TABLE IF NOT EXISTS vector_write_compensation (
  compensation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  embedding_id BIGINT NOT NULL UNIQUE REFERENCES feature_embedding(embedding_id) ON DELETE CASCADE,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(256) NULL,
  lock_until TIMESTAMPTZ NULL,
  last_error VARCHAR(2000) NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_write_compensation_status CHECK(status IN ('pending','processing','retry_wait','completed','dead_letter')),
  CONSTRAINT ck_vector_write_compensation_attempt CHECK(attempt_count >= 0)
);
CREATE INDEX IF NOT EXISTS idx_vector_write_compensation_work ON vector_write_compensation(status,available_at,lock_until,compensation_id);
CREATE INDEX IF NOT EXISTS idx_graph_projection_rebuild_status ON graph_projection_rebuild(status, created_at, rebuild_id);
INSERT INTO graph_projection_checkpoint(projection_name) VALUES('aura-domain-graph') ON CONFLICT(projection_name) DO NOTHING;
