-- 寓瞳系统 PostgreSQL 基础表结构
-- 目标：PostgreSQL 16+，UTF-8

CREATE TABLE IF NOT EXISTS sys_role (
  role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(64) NOT NULL,
  permission_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_user (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(64) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id BIGINT NOT NULL REFERENCES sys_role(role_id),
  status SMALLINT NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nvr_device (
  device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  ip VARCHAR(64) NOT NULL,
  port INT NOT NULL,
  brand VARCHAR(32) NOT NULL,
  protocol VARCHAR(32) NOT NULL,
  hmac_secret VARCHAR(255) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'offline',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_roi (
  roi_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id BIGINT NOT NULL,
  room_node_id BIGINT NOT NULL,
  vertices_json JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_floor (
  floor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  scale_ratio NUMERIC(10,4) NOT NULL DEFAULT 1.0000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS map_camera (
  camera_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor_id BIGINT NOT NULL,
  device_id BIGINT NOT NULL,
  channel_no INT NOT NULL,
  pos_x NUMERIC(12,4) NOT NULL DEFAULT 0,
  pos_y NUMERIC(12,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dict_campus (
  node_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT NULL,
  level_type VARCHAR(32) NOT NULL,
  node_name VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS capture_record (
  capture_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  channel_no INT NOT NULL,
  capture_time TIMESTAMP NOT NULL,
  image_path VARCHAR(255) NULL,
  feature_id VARCHAR(128) NULL,
  metadata_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS track_event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vid VARCHAR(64) NOT NULL,
  camera_id BIGINT NOT NULL,
  roi_id BIGINT NOT NULL,
  event_time TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS judge_result (
  judge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vid VARCHAR(64) NOT NULL,
  room_id BIGINT NOT NULL,
  judge_type VARCHAR(32) NOT NULL,
  judge_date DATE NOT NULL,
  detail_json JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS virtual_person (
  v_id VARCHAR(64) PRIMARY KEY,
  first_seen TIMESTAMP NOT NULL,
  last_seen TIMESTAMP NOT NULL,
  device_id BIGINT NOT NULL,
  capture_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_record (
  alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_type VARCHAR(32) NOT NULL,
  vid VARCHAR(64) NULL,
  room_id BIGINT NULL,
  detail_json JSONB NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_operation (
  op_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_name VARCHAR(64) NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  action_detail TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_system (
  system_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level VARCHAR(16) NOT NULL,
  source VARCHAR(64) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============ 表级注释 & 字段注释 ============
-- 说明：仅补充 COMMENT，不影响业务逻辑/约束/索引/数据初始化

COMMENT ON TABLE sys_role IS '系统角色表';
COMMENT ON COLUMN sys_role.role_id IS '角色ID';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.permission_json IS '角色权限（JSONB）';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';

COMMENT ON TABLE sys_user IS '系统用户表';
COMMENT ON COLUMN sys_user.user_id IS '用户ID';
COMMENT ON COLUMN sys_user.user_name IS '用户名';
COMMENT ON COLUMN sys_user.display_name IS '显示名称（用于页面展示）';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.role_id IS '角色ID（外键：sys_role.role_id）';
COMMENT ON COLUMN sys_user.status IS '状态（1启用，其他为禁用）';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';

COMMENT ON TABLE nvr_device IS 'NVR/摄像头设备表';
COMMENT ON COLUMN nvr_device.device_id IS '设备ID';
COMMENT ON COLUMN nvr_device.name IS '设备名称';
COMMENT ON COLUMN nvr_device.ip IS '设备IP';
COMMENT ON COLUMN nvr_device.port IS '设备端口';
COMMENT ON COLUMN nvr_device.brand IS '设备品牌';
COMMENT ON COLUMN nvr_device.protocol IS '设备协议（如 ONVIF/Hikvision 等）';
COMMENT ON COLUMN nvr_device.hmac_secret IS '设备 HMAC 密钥';
COMMENT ON COLUMN nvr_device.status IS '设备状态（例如 offline/online）';
COMMENT ON COLUMN nvr_device.created_at IS '创建时间';

COMMENT ON TABLE map_roi IS 'ROI（感兴趣区域）映射表';
COMMENT ON COLUMN map_roi.roi_id IS 'ROI ID';
COMMENT ON COLUMN map_roi.camera_id IS '所属摄像头ID';
COMMENT ON COLUMN map_roi.room_node_id IS '所属房间节点ID';
COMMENT ON COLUMN map_roi.vertices_json IS 'ROI 多边形顶点（JSONB）';
COMMENT ON COLUMN map_roi.created_at IS '创建时间';

COMMENT ON TABLE map_floor IS '楼层映射/配置表';
COMMENT ON COLUMN map_floor.floor_id IS '楼层ID';
COMMENT ON COLUMN map_floor.node_id IS '节点ID（对应 dict_campus 的层级节点）';
COMMENT ON COLUMN map_floor.file_path IS '楼层图文件路径';
COMMENT ON COLUMN map_floor.scale_ratio IS '楼层图缩放比例';
COMMENT ON COLUMN map_floor.created_at IS '创建时间';

COMMENT ON TABLE map_camera IS '摄像头与楼层/设备关系表';
COMMENT ON COLUMN map_camera.camera_id IS '摄像头ID';
COMMENT ON COLUMN map_camera.floor_id IS '楼层ID';
COMMENT ON COLUMN map_camera.device_id IS '设备ID（nvr_device.device_id）';
COMMENT ON COLUMN map_camera.channel_no IS '设备通道号';
COMMENT ON COLUMN map_camera.pos_x IS '摄像头在楼层图的 X 坐标';
COMMENT ON COLUMN map_camera.pos_y IS '摄像头在楼层图的 Y 坐标';
COMMENT ON COLUMN map_camera.created_at IS '创建时间';

COMMENT ON TABLE dict_campus IS '校园/楼栋/房间等层级字典表';
COMMENT ON COLUMN dict_campus.node_id IS '节点ID';
COMMENT ON COLUMN dict_campus.parent_id IS '父节点ID';
COMMENT ON COLUMN dict_campus.level_type IS '层级类型（如 campus/building/floor/room）';
COMMENT ON COLUMN dict_campus.node_name IS '节点名称';
COMMENT ON COLUMN dict_campus.created_at IS '创建时间';

COMMENT ON TABLE capture_record IS '抓拍记录表';
COMMENT ON COLUMN capture_record.capture_id IS '抓拍记录ID';
COMMENT ON COLUMN capture_record.device_id IS '设备ID';
COMMENT ON COLUMN capture_record.channel_no IS '通道号';
COMMENT ON COLUMN capture_record.capture_time IS '抓拍时间';
COMMENT ON COLUMN capture_record.image_path IS '抓拍图片路径（可空）';
COMMENT ON COLUMN capture_record.feature_id IS '特征ID/向量ID（可空）';
COMMENT ON COLUMN capture_record.metadata_json IS '抓拍元数据（JSONB，可空）';
COMMENT ON COLUMN capture_record.created_at IS '创建时间';

COMMENT ON TABLE track_event IS '目标/人员轨迹事件表';
COMMENT ON COLUMN track_event.event_id IS '轨迹事件ID';
COMMENT ON COLUMN track_event.vid IS '目标ID（通常对应特征向量ID）';
COMMENT ON COLUMN track_event.camera_id IS '摄像头ID';
COMMENT ON COLUMN track_event.roi_id IS 'ROI ID';
COMMENT ON COLUMN track_event.event_time IS '事件时间';
COMMENT ON COLUMN track_event.created_at IS '创建时间';

COMMENT ON TABLE judge_result IS '研判结果表';
COMMENT ON COLUMN judge_result.judge_id IS '研判结果ID';
COMMENT ON COLUMN judge_result.vid IS '目标ID（通常对应特征向量ID）';
COMMENT ON COLUMN judge_result.room_id IS '房间ID';
COMMENT ON COLUMN judge_result.judge_type IS '研判类型';
COMMENT ON COLUMN judge_result.judge_date IS '研判日期';
COMMENT ON COLUMN judge_result.detail_json IS '研判详情（JSONB，可空）';
COMMENT ON COLUMN judge_result.created_at IS '创建时间';

COMMENT ON TABLE virtual_person IS '虚拟人员/追踪聚合表';
COMMENT ON COLUMN virtual_person.v_id IS '虚拟人员ID';
COMMENT ON COLUMN virtual_person.first_seen IS '首次出现时间';
COMMENT ON COLUMN virtual_person.last_seen IS '最后出现时间';
COMMENT ON COLUMN virtual_person.device_id IS '设备ID';
COMMENT ON COLUMN virtual_person.capture_count IS '出现次数';
COMMENT ON COLUMN virtual_person.created_at IS '创建时间';

COMMENT ON TABLE alert_record IS '告警记录表';
COMMENT ON COLUMN alert_record.alert_id IS '告警ID';
COMMENT ON COLUMN alert_record.alert_type IS '告警类型';
COMMENT ON COLUMN alert_record.vid IS '目标ID（可空）';
COMMENT ON COLUMN alert_record.room_id IS '房间ID（可空）';
COMMENT ON COLUMN alert_record.detail_json IS '告警详情（JSONB，可空）';
COMMENT ON COLUMN alert_record.created_at IS '创建时间';

COMMENT ON TABLE log_operation IS '系统操作日志表';
COMMENT ON COLUMN log_operation.op_id IS '操作日志ID';
COMMENT ON COLUMN log_operation.operator_name IS '操作员用户名';
COMMENT ON COLUMN log_operation.action_type IS '动作类型';
COMMENT ON COLUMN log_operation.action_detail IS '动作详情';
COMMENT ON COLUMN log_operation.created_at IS '创建时间';

COMMENT ON TABLE log_system IS '系统运行日志表';
COMMENT ON COLUMN log_system.system_log_id IS '系统日志ID';
COMMENT ON COLUMN log_system.level IS '日志级别';
COMMENT ON COLUMN log_system.source IS '日志来源';
COMMENT ON COLUMN log_system.message IS '日志内容';
COMMENT ON COLUMN log_system.created_at IS '创建时间';

CREATE INDEX IF NOT EXISTS idx_capture_time_desc
  ON capture_record(capture_time, capture_id);

CREATE INDEX IF NOT EXISTS idx_track_event_time_desc
  ON track_event(event_time, event_id);

CREATE INDEX IF NOT EXISTS idx_track_event_vid_desc
  ON track_event(vid, event_id);

CREATE INDEX IF NOT EXISTS idx_judge_date_type_desc
  ON judge_result(judge_date, judge_type, judge_id);

CREATE INDEX IF NOT EXISTS idx_alert_id_desc
  ON alert_record(alert_id);

CREATE INDEX IF NOT EXISTS idx_log_system_id_desc
  ON log_system(system_log_id);

INSERT INTO sys_role (role_id, role_name, permission_json)
VALUES
  (1, 'super_admin', '["all"]'::jsonb),
  (2, 'building_admin', '["device","roi","track","alert","stats"]'::jsonb)
ON CONFLICT (role_id) DO NOTHING;
