-- Extension foundations for alert workflow, space analytics, reports, tenants, and AI platform configuration.

CREATE TABLE IF NOT EXISTS alert_workflow (
  workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id BIGINT NOT NULL REFERENCES alert_record(alert_id) ON DELETE CASCADE,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  assignee VARCHAR(64) NULL,
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  escalation_level INT NOT NULL DEFAULT 0,
  handover_to VARCHAR(64) NULL,
  note TEXT NULL,
  closed_at TIMESTAMP NULL,
  updated_by VARCHAR(64) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS space_topology_edge (
  edge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_camera_id BIGINT NOT NULL,
  to_camera_id BIGINT NOT NULL,
  relation_type VARCHAR(32) NOT NULL DEFAULT 'walkable',
  weight NUMERIC(10,4) NOT NULL DEFAULT 1.0000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS space_heatmap_snapshot (
  snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor_id BIGINT NOT NULL,
  bucket_start TIMESTAMP NOT NULL,
  bucket_minutes INT NOT NULL DEFAULT 60,
  heat_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_schedule (
  schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_type VARCHAR(32) NOT NULL,
  cron_expr VARCHAR(64) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  delivery_channel VARCHAR(32) NOT NULL DEFAULT 'system',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by VARCHAR(64) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_run (
  run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NULL REFERENCES report_schedule(schedule_id) ON DELETE SET NULL,
  report_type VARCHAR(32) NOT NULL,
  range_start DATE NOT NULL,
  range_end DATE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'generated',
  summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(64) NULL,
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_delivery (
  delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES report_run(run_id) ON DELETE CASCADE,
  role_name VARCHAR(64) NOT NULL,
  delivery_channel VARCHAR(32) NOT NULL DEFAULT 'system',
  status VARCHAR(32) NOT NULL DEFAULT 'delivered',
  delivered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_project (
  tenant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_code VARCHAR(64) NOT NULL UNIQUE,
  tenant_name VARCHAR(128) NOT NULL,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_role_scope (
  scope_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  role_name VARCHAR(64) NOT NULL,
  permission_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_provider_config (
  provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name VARCHAR(64) NOT NULL,
  provider_type VARCHAR(32) NOT NULL,
  endpoint_url TEXT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  traffic_weight INT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_ab_experiment (
  experiment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  experiment_name VARCHAR(128) NOT NULL,
  provider_a_id BIGINT NOT NULL REFERENCES ai_provider_config(provider_id),
  provider_b_id BIGINT NOT NULL REFERENCES ai_provider_config(provider_id),
  traffic_split INT NOT NULL DEFAULT 50,
  metric_name VARCHAR(64) NOT NULL DEFAULT 'recall_at_k',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_workflow_alert_updated
  ON alert_workflow(alert_id, updated_at DESC, workflow_id DESC);

CREATE INDEX IF NOT EXISTS idx_alert_workflow_status_updated
  ON alert_workflow(status, updated_at DESC, workflow_id DESC);

CREATE INDEX IF NOT EXISTS idx_space_topology_from_camera
  ON space_topology_edge(from_camera_id, to_camera_id);

CREATE INDEX IF NOT EXISTS idx_space_heatmap_floor_bucket
  ON space_heatmap_snapshot(floor_id, bucket_start DESC, snapshot_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_schedule_type_enabled
  ON report_schedule(report_type, enabled, schedule_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_run_type_generated
  ON report_run(report_type, generated_at DESC, run_id DESC);

CREATE INDEX IF NOT EXISTS idx_report_delivery_role_status
  ON report_delivery(role_name, status, delivered_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_role_scope
  ON tenant_role_scope(tenant_id, role_name);

CREATE INDEX IF NOT EXISTS idx_tenant_role_scope_role
  ON tenant_role_scope(role_name, tenant_id);

CREATE INDEX IF NOT EXISTS idx_ai_provider_enabled_weight
  ON ai_provider_config(enabled, traffic_weight DESC, provider_id DESC);
