-- Generic media-analysis provider control plane.

CREATE TABLE IF NOT EXISTS media_analysis_provider (
  provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_code VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  adapter_type VARCHAR(64) NOT NULL DEFAULT 'standard_http',
  base_url TEXT NOT NULL,
  auth_type VARCHAR(32) NOT NULL DEFAULT 'hmac',
  secret_ref VARCHAR(255) NULL,
  capabilities_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  protocol_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  timeout_seconds INT NOT NULL DEFAULT 10,
  max_concurrency INT NOT NULL DEFAULT 16,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_analysis_provider_timeout CHECK (timeout_seconds BETWEEN 1 AND 300),
  CONSTRAINT ck_media_analysis_provider_concurrency CHECK (max_concurrency BETWEEN 1 AND 10000),
  CONSTRAINT ck_media_analysis_provider_auth CHECK (auth_type IN ('none', 'hmac', 'bearer', 'oauth2_client', 'mtls'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_media_analysis_provider_scope_code
  ON media_analysis_provider(COALESCE(tenant_id, 0), provider_code);

CREATE INDEX IF NOT EXISTS idx_media_analysis_provider_enabled
  ON media_analysis_provider(enabled, tenant_id, provider_id);

CREATE TABLE IF NOT EXISTS media_analysis_pipeline (
  pipeline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  pipeline_code VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  model_name VARCHAR(128) NOT NULL DEFAULT '',
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  input_types_json JSONB NOT NULL DEFAULT '["image"]'::jsonb,
  output_types_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  embedding_dimension INT NULL,
  default_options_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_analysis_pipeline_dimension CHECK (embedding_dimension IS NULL OR embedding_dimension BETWEEN 1 AND 65535),
  CONSTRAINT ux_media_analysis_pipeline_version UNIQUE(provider_id, pipeline_code, model_version)
);

CREATE INDEX IF NOT EXISTS idx_media_analysis_pipeline_enabled
  ON media_analysis_pipeline(provider_id, enabled, pipeline_id);

CREATE TABLE IF NOT EXISTS media_source (
  source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  camera_id BIGINT NOT NULL REFERENCES map_camera(camera_id) ON DELETE CASCADE,
  source_code VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'rtsp',
  uri_template TEXT NOT NULL,
  credential_ref VARCHAR(255) NULL,
  stream_profile VARCHAR(32) NOT NULL DEFAULT 'sub',
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  config_version BIGINT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_source_type CHECK (source_type IN ('rtsp', 'http', 'https', 'file', 'object')),
  CONSTRAINT ux_media_source_tenant_code UNIQUE(tenant_id, source_code),
  CONSTRAINT ux_media_source_tenant_camera_profile UNIQUE(tenant_id, camera_id, stream_profile)
);

CREATE INDEX IF NOT EXISTS idx_media_source_camera_enabled
  ON media_source(camera_id, enabled, source_id);

CREATE TABLE IF NOT EXISTS media_analysis_subscription (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  source_id BIGINT NOT NULL REFERENCES media_source(source_id) ON DELETE CASCADE,
  pipeline_id BIGINT NOT NULL REFERENCES media_analysis_pipeline(pipeline_id),
  client_subscription_id VARCHAR(128) NOT NULL,
  external_subscription_id VARCHAR(255) NULL,
  desired_state VARCHAR(32) NOT NULL DEFAULT 'stopped',
  observed_state VARCHAR(32) NOT NULL DEFAULT 'unknown',
  desired_config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  applied_config_hash VARCHAR(64) NULL,
  last_heartbeat_at TIMESTAMPTZ NULL,
  last_reconciled_at TIMESTAMPTZ NULL,
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  version BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_analysis_subscription_client UNIQUE(client_subscription_id),
  CONSTRAINT ux_media_analysis_subscription_target UNIQUE(tenant_id, source_id, pipeline_id),
  CONSTRAINT ck_media_analysis_subscription_desired CHECK (desired_state IN ('stopped', 'running')),
  CONSTRAINT ck_media_analysis_subscription_observed CHECK (observed_state IN ('unknown', 'starting', 'running', 'degraded', 'stopping', 'stopped', 'failed')),
  CONSTRAINT ck_media_analysis_subscription_retry CHECK (retry_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_media_analysis_subscription_reconcile
  ON media_analysis_subscription(desired_state, observed_state, next_retry_at, subscription_id);

CREATE INDEX IF NOT EXISTS idx_media_analysis_subscription_heartbeat
  ON media_analysis_subscription(observed_state, last_heartbeat_at)
  WHERE observed_state IN ('starting', 'running', 'degraded');

CREATE TABLE IF NOT EXISTS media_analysis_job (
  job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  pipeline_id BIGINT NOT NULL REFERENCES media_analysis_pipeline(pipeline_id),
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  external_job_id VARCHAR(255) NULL,
  media_type VARCHAR(32) NOT NULL,
  media_uri TEXT NULL,
  request_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  progress NUMERIC(5,2) NOT NULL DEFAULT 0,
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ NULL,
  error_code VARCHAR(64) NULL,
  error_message TEXT NULL,
  submitted_at TIMESTAMPTZ NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_media_analysis_job_idempotency UNIQUE(provider_id, idempotency_key),
  CONSTRAINT ck_media_analysis_job_type CHECK (media_type IN ('image', 'video')),
  CONSTRAINT ck_media_analysis_job_status CHECK (status IN ('pending', 'submitting', 'accepted', 'running', 'completed', 'rejected', 'cancelling', 'cancelled', 'failed', 'retry_wait')),
  CONSTRAINT ck_media_analysis_job_progress CHECK (progress BETWEEN 0 AND 100),
  CONSTRAINT ck_media_analysis_job_retry CHECK (retry_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_media_analysis_job_work
  ON media_analysis_job(status, next_retry_at, job_id);

CREATE INDEX IF NOT EXISTS idx_media_analysis_job_tenant_created
  ON media_analysis_job(tenant_id, created_at DESC, job_id DESC);
