-- Reliable ingress, normalized events, artifacts, and transactional outbox.

CREATE TABLE IF NOT EXISTS integration_webhook_nonce (
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  nonce VARCHAR(128) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(provider_id, nonce)
);

CREATE INDEX IF NOT EXISTS idx_integration_webhook_nonce_expiry
  ON integration_webhook_nonce(expires_at);

CREATE TABLE IF NOT EXISTS media_analysis_inbox (
  inbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id),
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id),
  event_id VARCHAR(128) NOT NULL,
  provider_event_id VARCHAR(255) NULL,
  subscription_id BIGINT NULL REFERENCES media_analysis_subscription(subscription_id) ON DELETE SET NULL,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  sequence_no BIGINT NULL,
  schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  event_type VARCHAR(64) NOT NULL,
  event_time TIMESTAMPTZ NOT NULL,
  produced_at TIMESTAMPTZ NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payload_json JSONB NOT NULL,
  payload_hash VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'received',
  attempt_count INT NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NULL,
  locked_by VARCHAR(128) NULL,
  lock_until TIMESTAMPTZ NULL,
  processed_at TIMESTAMPTZ NULL,
  last_error_code VARCHAR(64) NULL,
  last_error TEXT NULL,
  trace_id VARCHAR(64) NULL,
  CONSTRAINT ux_media_analysis_inbox_provider_event UNIQUE(provider_id, event_id),
  CONSTRAINT ck_media_analysis_inbox_status CHECK (status IN ('received', 'processing', 'processed', 'retry_wait', 'dead_letter', 'unsupported')),
  CONSTRAINT ck_media_analysis_inbox_attempt CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_work
  ON media_analysis_inbox(status, next_attempt_at, lock_until, inbox_id);

CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_tenant_received
  ON media_analysis_inbox(tenant_id, received_at DESC, inbox_id DESC);

CREATE INDEX IF NOT EXISTS idx_media_analysis_inbox_subscription_sequence
  ON media_analysis_inbox(subscription_id, sequence_no)
  WHERE subscription_id IS NOT NULL AND sequence_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS media_analysis_event (
  analysis_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inbox_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_inbox(inbox_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id),
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  subscription_id BIGINT NULL REFERENCES media_analysis_subscription(subscription_id) ON DELETE SET NULL,
  event_type VARCHAR(64) NOT NULL,
  event_time TIMESTAMPTZ NOT NULL,
  track_id VARCHAR(255) NULL,
  entity_id VARCHAR(255) NULL,
  embedding_id VARCHAR(255) NULL,
  confidence NUMERIC(8,6) NULL,
  late_event BOOLEAN NOT NULL DEFAULT FALSE,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_analysis_event_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

CREATE INDEX IF NOT EXISTS idx_media_analysis_event_source_time
  ON media_analysis_event(tenant_id, source_id, event_time DESC, analysis_event_id DESC);

CREATE INDEX IF NOT EXISTS idx_media_analysis_event_type_time
  ON media_analysis_event(tenant_id, event_type, event_time DESC, analysis_event_id DESC);

CREATE INDEX IF NOT EXISTS idx_media_analysis_event_track_time
  ON media_analysis_event(tenant_id, track_id, event_time, analysis_event_id)
  WHERE track_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_media_analysis_event_entity_time
  ON media_analysis_event(tenant_id, entity_id, event_time DESC, analysis_event_id DESC)
  WHERE entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS integration_outbox (
  outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload_json JSONB NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(128) NULL,
  lock_until TIMESTAMPTZ NULL,
  processed_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_integration_outbox_status CHECK (status IN ('pending', 'processing', 'processed', 'retry_wait', 'dead_letter')),
  CONSTRAINT ck_integration_outbox_attempt CHECK (attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_integration_outbox_work
  ON integration_outbox(status, available_at, lock_until, outbox_id);

CREATE INDEX IF NOT EXISTS idx_integration_outbox_aggregate
  ON integration_outbox(aggregate_type, aggregate_id, outbox_id DESC);

CREATE TABLE IF NOT EXISTS media_artifact (
  artifact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  analysis_event_id BIGINT NULL REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL,
  provider_uri TEXT NULL,
  archive_uri TEXT NULL,
  media_type VARCHAR(64) NOT NULL,
  content_type VARCHAR(128) NULL,
  size_bytes BIGINT NULL,
  sha256 VARCHAR(64) NULL,
  archive_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  expires_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_artifact_size CHECK (size_bytes IS NULL OR size_bytes >= 0),
  CONSTRAINT ck_media_artifact_status CHECK (archive_status IN ('pending', 'archiving', 'archived', 'failed', 'not_required'))
);

CREATE INDEX IF NOT EXISTS idx_media_artifact_archive_work
  ON media_artifact(archive_status, expires_at, artifact_id);
