-- Aura-owned 512-dimensional Re-ID embeddings.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embedding_model (
  model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE SET NULL,
  model_code VARCHAR(128) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  model_version VARCHAR(64) NOT NULL DEFAULT 'default',
  dimension INT NOT NULL DEFAULT 512,
  distance_metric VARCHAR(32) NOT NULL DEFAULT 'cosine',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_embedding_model_code_version UNIQUE(model_code, model_version),
  CONSTRAINT ck_embedding_model_dimension CHECK (dimension = 512),
  CONSTRAINT ck_embedding_model_metric CHECK (distance_metric IN ('cosine'))
);

CREATE TABLE IF NOT EXISTS feature_embedding (
  embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  external_embedding_id VARCHAR(255) NULL,
  vid VARCHAR(128) NOT NULL,
  capture_id BIGINT NULL REFERENCES capture_record(capture_id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES embedding_model(model_id),
  feature vector(512) NOT NULL,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_feature_embedding_sample UNIQUE(tenant_id, model_id, vid, capture_id)
);

CREATE INDEX IF NOT EXISTS idx_feature_embedding_tenant_model_vid
  ON feature_embedding(tenant_id, model_id, vid, embedding_id DESC);

CREATE INDEX IF NOT EXISTS idx_feature_embedding_capture
  ON feature_embedding(capture_id)
  WHERE capture_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_feature_embedding_feature_hnsw
  ON feature_embedding USING hnsw (feature vector_cosine_ops);
