-- ArangoDB graph projection state and rebuild audit.

CREATE TABLE IF NOT EXISTS graph_projection_checkpoint (
  projection_name VARCHAR(128) PRIMARY KEY,
  last_outbox_id BIGINT NULL,
  last_projected_at TIMESTAMPTZ NULL,
  graph_version VARCHAR(64) NOT NULL DEFAULT '1',
  status VARCHAR(32) NOT NULL DEFAULT 'idle',
  last_error TEXT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_graph_projection_checkpoint_status CHECK (status IN ('idle', 'running', 'degraded', 'failed', 'rebuilding'))
);

CREATE TABLE IF NOT EXISTS graph_projection_rebuild (
  rebuild_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  projection_name VARCHAR(128) NOT NULL,
  requested_by VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  processed_vertices BIGINT NOT NULL DEFAULT 0,
  processed_edges BIGINT NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_graph_projection_rebuild_status CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_graph_projection_rebuild_status
  ON graph_projection_rebuild(status, created_at, rebuild_id);

INSERT INTO graph_projection_checkpoint(projection_name)
VALUES('aura-domain-graph')
ON CONFLICT(projection_name) DO NOTHING;
