-- Media-analysis business facts, idempotency hardening, worker health and vector migration evidence.

ALTER TABLE media_analysis_subscription
  ADD COLUMN IF NOT EXISTS last_sequence_no BIGINT NULL,
  ADD COLUMN IF NOT EXISTS last_event_time TIMESTAMPTZ NULL;

ALTER TABLE capture_record
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS camera_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS embedding_id BIGINT NULL;

ALTER TABLE capture_record ALTER COLUMN image_path TYPE TEXT;

ALTER TABLE alert_record
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS model_code VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS model_version VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS confidence NUMERIC(8,6) NULL;

ALTER TABLE judge_result
  ADD COLUMN IF NOT EXISTS tenant_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS analysis_event_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS model_code VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS model_version VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS confidence NUMERIC(8,6) NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_tenant') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_camera') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_camera
      FOREIGN KEY(camera_id) REFERENCES map_camera(camera_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_analysis_event') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_capture_record_embedding') THEN
    ALTER TABLE capture_record ADD CONSTRAINT fk_capture_record_embedding
      FOREIGN KEY(embedding_id) REFERENCES feature_embedding(embedding_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_alert_record_tenant') THEN
    ALTER TABLE alert_record ADD CONSTRAINT fk_alert_record_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_alert_record_analysis_event') THEN
    ALTER TABLE alert_record ADD CONSTRAINT fk_alert_record_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_judge_result_tenant') THEN
    ALTER TABLE judge_result ADD CONSTRAINT fk_judge_result_tenant
      FOREIGN KEY(tenant_id) REFERENCES tenant_project(tenant_id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_judge_result_analysis_event') THEN
    ALTER TABLE judge_result ADD CONSTRAINT fk_judge_result_analysis_event
      FOREIGN KEY(analysis_event_id) REFERENCES media_analysis_event(analysis_event_id) ON DELETE SET NULL NOT VALID;
  END IF;
END $$;

ALTER TABLE feature_embedding DROP CONSTRAINT IF EXISTS ux_feature_embedding_sample;
CREATE UNIQUE INDEX IF NOT EXISTS ux_feature_embedding_sample
  ON feature_embedding(tenant_id,model_id,vid,capture_id) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX IF NOT EXISTS ux_integration_outbox_aggregate_event
  ON integration_outbox(aggregate_type, aggregate_id, event_type);
CREATE UNIQUE INDEX IF NOT EXISTS ux_media_artifact_event_uri
  ON media_artifact(analysis_event_id, provider_uri);
CREATE UNIQUE INDEX IF NOT EXISTS ux_track_event_natural
  ON track_event(vid, camera_id, event_time);
CREATE UNIQUE INDEX IF NOT EXISTS ux_capture_record_analysis_event
  ON capture_record(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_alert_record_analysis_event
  ON alert_record(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_judge_result_analysis_event
  ON judge_result(analysis_event_id) WHERE analysis_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_capture_record_tenant_camera_time
  ON capture_record(tenant_id, camera_id, capture_time DESC);

CREATE TABLE IF NOT EXISTS media_detection_fact (
  detection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  camera_id BIGINT NULL REFERENCES map_camera(camera_id) ON DELETE SET NULL,
  provider_track_id VARCHAR(256) NULL,
  object_type VARCHAR(128) NOT NULL,
  bbox_json JSONB NULL,
  confidence NUMERIC(8,6) NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  event_time TIMESTAMPTZ NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_detection_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1)
);
CREATE INDEX IF NOT EXISTS idx_media_detection_tenant_source_time
  ON media_detection_fact(tenant_id, source_id, event_time DESC);

CREATE TABLE IF NOT EXISTS media_track_binding (
  track_binding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  provider_id BIGINT NOT NULL REFERENCES media_analysis_provider(provider_id) ON DELETE CASCADE,
  source_id BIGINT NULL REFERENCES media_source(source_id) ON DELETE SET NULL,
  provider_track_id VARCHAR(256) NOT NULL,
  aura_track_id VARCHAR(64) NOT NULL,
  entity_id VARCHAR(128) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  last_sequence_no BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_track_binding_status CHECK(status IN ('active','ended')),
  CONSTRAINT ux_media_track_provider_track UNIQUE(tenant_id,provider_id,source_id,provider_track_id)
);
CREATE INDEX IF NOT EXISTS idx_media_track_binding_aura
  ON media_track_binding(tenant_id,aura_track_id,last_seen DESC);

CREATE TABLE IF NOT EXISTS media_identity_candidate (
  candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  track_binding_id BIGINT NULL REFERENCES media_track_binding(track_binding_id) ON DELETE SET NULL,
  candidate_vid VARCHAR(64) NULL,
  embedding_id BIGINT NULL REFERENCES feature_embedding(embedding_id) ON DELETE SET NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  confidence NUMERIC(8,6) NULL,
  decision VARCHAR(32) NOT NULL DEFAULT 'pending',
  decision_reason VARCHAR(512) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_media_identity_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1),
  CONSTRAINT ck_media_identity_decision CHECK(decision IN ('pending','linked','rejected','review'))
);
CREATE INDEX IF NOT EXISTS idx_media_identity_candidate_review
  ON media_identity_candidate(tenant_id,decision,created_at DESC);

CREATE TABLE IF NOT EXISTS media_behavior_fact (
  behavior_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analysis_event_id BIGINT NOT NULL UNIQUE REFERENCES media_analysis_event(analysis_event_id) ON DELETE CASCADE,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  behavior_type VARCHAR(128) NOT NULL,
  provider_track_id VARCHAR(256) NULL,
  entity_id VARCHAR(128) NULL,
  room_id BIGINT NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  confidence NUMERIC(8,6) NULL,
  event_time TIMESTAMPTZ NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_media_behavior_confidence CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1)
);
CREATE INDEX IF NOT EXISTS idx_media_behavior_tenant_type_time
  ON media_behavior_fact(tenant_id,behavior_type,event_time DESC);

CREATE TABLE IF NOT EXISTS background_worker_heartbeat (
  worker_name VARCHAR(128) NOT NULL,
  instance_id VARCHAR(256) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  last_success_at TIMESTAMPTZ NULL,
  last_error_at TIMESTAMPTZ NULL,
  last_error VARCHAR(2000) NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(worker_name,instance_id)
);
CREATE INDEX IF NOT EXISTS idx_background_worker_heartbeat_updated
  ON background_worker_heartbeat(worker_name,updated_at DESC);

CREATE TABLE IF NOT EXISTS vector_migration_checkpoint (
  migration_name VARCHAR(128) PRIMARY KEY,
  source_engine VARCHAR(64) NOT NULL,
  target_engine VARCHAR(64) NOT NULL,
  last_source_key VARCHAR(512) NULL,
  scanned_count BIGINT NOT NULL DEFAULT 0,
  migrated_count BIGINT NOT NULL DEFAULT 0,
  skipped_count BIGINT NOT NULL DEFAULT 0,
  failed_count BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'idle',
  last_error VARCHAR(2000) NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_migration_checkpoint_status CHECK(status IN ('idle','running','completed','failed','cancelled'))
);

CREATE TABLE IF NOT EXISTS vector_shadow_evaluation (
  evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE CASCADE,
  model_id BIGINT NOT NULL REFERENCES embedding_model(model_id) ON DELETE CASCADE,
  sample_count INT NOT NULL,
  top_k INT NOT NULL,
  recall_at_k NUMERIC(10,8) NULL,
  mrr NUMERIC(10,8) NULL,
  topk_overlap NUMERIC(10,8) NULL,
  empty_result_rate NUMERIC(10,8) NULL,
  pgvector_p95_ms NUMERIC(14,4) NULL,
  legacy_p95_ms NUMERIC(14,4) NULL,
  report_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_shadow_sample CHECK(sample_count > 0 AND top_k > 0)
);
CREATE INDEX IF NOT EXISTS idx_vector_shadow_evaluation_model_time
  ON vector_shadow_evaluation(tenant_id,model_id,created_at DESC);
