-- Durable retry queue for the temporary pgvector/legacy dual-write period.

CREATE TABLE IF NOT EXISTS vector_write_compensation (
  compensation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  embedding_id BIGINT NOT NULL UNIQUE REFERENCES feature_embedding(embedding_id) ON DELETE CASCADE,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(256) NULL,
  lock_until TIMESTAMPTZ NULL,
  last_error VARCHAR(2000) NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_vector_write_compensation_status
    CHECK(status IN ('pending','processing','retry_wait','completed','dead_letter')),
  CONSTRAINT ck_vector_write_compensation_attempt CHECK(attempt_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_vector_write_compensation_work
  ON vector_write_compensation(status,available_at,lock_until,compensation_id);
