-- Commercial release governance and authoritative event/case workflow.

CREATE TABLE IF NOT EXISTS service_profile (
  profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_code VARCHAR(64) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  delivery_mode VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  profile_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_by VARCHAR(128) NULL,
  approved_at TIMESTAMPTZ NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_service_profile_version UNIQUE(profile_code,version),
  CONSTRAINT ck_service_profile_delivery CHECK(delivery_mode IN ('private_standard','private_ha','managed_pilot')),
  CONSTRAINT ck_service_profile_status CHECK(status IN ('draft','approved','superseded'))
);

CREATE TABLE IF NOT EXISTS release_gate_run (
  gate_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_profile_id BIGINT NOT NULL REFERENCES service_profile(profile_id),
  build_version VARCHAR(64) NOT NULL,
  git_commit VARCHAR(64) NOT NULL,
  image_digest VARCHAR(256) NULL,
  migration_version VARCHAR(64) NOT NULL,
  environment_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(24) NOT NULL DEFAULT 'blocked',
  exception_json JSONB NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ NULL,
  created_by VARCHAR(128) NOT NULL,
  CONSTRAINT ck_release_gate_status CHECK(status IN ('running','passed','failed','blocked','exception'))
);
CREATE INDEX IF NOT EXISTS idx_release_gate_build ON release_gate_run(build_version,started_at DESC);

CREATE TABLE IF NOT EXISTS product_capability (
  capability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capability_code VARCHAR(64) NOT NULL,
  product_version VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL,
  supported_targets_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  limitations_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_uri TEXT NULL,
  owner VARCHAR(128) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_product_capability_version UNIQUE(capability_code,product_version),
  CONSTRAINT ck_product_capability_status CHECK(status IN ('supported','experimental','planned','deprecated'))
);

CREATE TABLE IF NOT EXISTS ops_high_risk_task (
  task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  operation_type VARCHAR(64) NOT NULL,
  scope_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  impact_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_hash VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'previewed',
  progress INT NOT NULL DEFAULT 0,
  confirmation_phrase VARCHAR(128) NULL,
  ticket_no VARCHAR(128) NULL,
  step_up_verified BOOLEAN NOT NULL DEFAULT FALSE,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  requested_by VARCHAR(128) NOT NULL,
  trace_id VARCHAR(128) NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 1,
  CONSTRAINT ux_ops_task_idempotency UNIQUE(requested_by,operation_type,idempotency_key),
  CONSTRAINT ck_ops_task_progress CHECK(progress BETWEEN 0 AND 100),
  CONSTRAINT ck_ops_task_status CHECK(status IN ('previewed','pending_confirmation','queued','running','succeeded','failed','cancelled'))
);

CREATE TABLE IF NOT EXISTS ops_high_risk_task_activity (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES ops_high_risk_task(task_id) ON DELETE RESTRICT,
  activity_type VARCHAR(64) NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor VARCHAR(128) NOT NULL,
  trace_id VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ops_task_status_created ON ops_high_risk_task(status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ops_task_activity_task ON ops_high_risk_task_activity(task_id,activity_id);

CREATE TABLE IF NOT EXISTS api_idempotency_record (
  idempotency_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  command_scope VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ux_api_idempotency_scope UNIQUE(tenant_id,command_scope,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_api_idempotency_expiry ON api_idempotency_record(expires_at);

CREATE TABLE IF NOT EXISTS business_event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  event_no VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  title VARCHAR(256) NOT NULL,
  summary TEXT NULL,
  severity VARCHAR(16) NOT NULL DEFAULT 'medium',
  status VARCHAR(24) NOT NULL DEFAULT 'open',
  triage_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  triage_user_name VARCHAR(128) NULL,
  rule_code VARCHAR(128) NULL,
  rule_version INT NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  entity_ref VARCHAR(256) NULL,
  space_ref VARCHAR(256) NULL,
  aggregation_key VARCHAR(512) NOT NULL,
  aggregation_policy_version INT NOT NULL DEFAULT 1,
  occurrence_count INT NOT NULL DEFAULT 1,
  first_occurred_at TIMESTAMPTZ NOT NULL,
  last_occurred_at TIMESTAMPTZ NOT NULL,
  representative_evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_business_event_no UNIQUE(tenant_id,event_no),
  CONSTRAINT ux_business_event_aggregation UNIQUE(tenant_id,aggregation_key,aggregation_policy_version),
  CONSTRAINT ck_business_event_status CHECK(status IN ('open','acknowledged','dismissed','linked')),
  CONSTRAINT ck_business_event_severity CHECK(severity IN ('low','medium','high','critical')),
  CONSTRAINT ck_business_event_occurrence CHECK(occurrence_count > 0)
);
CREATE INDEX IF NOT EXISTS idx_business_event_tenant_status_time ON business_event(tenant_id,status,last_occurred_at DESC,event_id DESC);

CREATE TABLE IF NOT EXISTS business_event_source (
  source_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  business_event_id BIGINT NOT NULL REFERENCES business_event(event_id) ON DELETE RESTRICT,
  analysis_event_id BIGINT NOT NULL REFERENCES media_analysis_event(analysis_event_id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_business_event_source UNIQUE(tenant_id,business_event_id,analysis_event_id)
);

CREATE TABLE IF NOT EXISTS business_event_activity (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  business_event_id BIGINT NOT NULL REFERENCES business_event(event_id) ON DELETE RESTRICT,
  activity_type VARCHAR(64) NOT NULL,
  from_status VARCHAR(24) NULL,
  to_status VARCHAR(24) NULL,
  reason_code VARCHAR(64) NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  actor_name VARCHAR(128) NOT NULL,
  trace_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_business_event_activity_key UNIQUE(tenant_id,business_event_id,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_business_event_activity_event ON business_event_activity(tenant_id,business_event_id,activity_id);

CREATE TABLE IF NOT EXISTS incident_case (
  case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_no VARCHAR(64) NOT NULL,
  title VARCHAR(256) NOT NULL,
  description TEXT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'new',
  status_reason VARCHAR(512) NULL,
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  owner_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  owner_name VARCHAR(128) NULL,
  organization VARCHAR(256) NULL,
  tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  external_ticket_no VARCHAR(128) NULL,
  sla_policy_version INT NOT NULL DEFAULT 1,
  acknowledge_due_at TIMESTAMPTZ NULL,
  start_due_at TIMESTAMPTZ NULL,
  resolve_due_at TIMESTAMPTZ NULL,
  paused_at TIMESTAMPTZ NULL,
  accumulated_pause_seconds BIGINT NOT NULL DEFAULT 0,
  escalation_level INT NOT NULL DEFAULT 0,
  resolution_json JSONB NULL,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMPTZ NULL,
  CONSTRAINT ux_incident_case_no UNIQUE(tenant_id,case_no),
  CONSTRAINT ck_incident_case_status CHECK(status IN ('new','acknowledged','in_progress','paused','escalated','resolved','false_positive','closed','reopened')),
  CONSTRAINT ck_incident_case_priority CHECK(priority IN ('low','normal','high','urgent')),
  CONSTRAINT ck_incident_case_pause CHECK(accumulated_pause_seconds >= 0)
);
CREATE INDEX IF NOT EXISTS idx_incident_case_tenant_status_time ON incident_case(tenant_id,status,updated_at DESC,case_id DESC);

CREATE TABLE IF NOT EXISTS incident_case_event (
  relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  event_id BIGINT NOT NULL REFERENCES business_event(event_id) ON DELETE RESTRICT,
  relation_type VARCHAR(32) NOT NULL DEFAULT 'primary',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  relation_reason VARCHAR(512) NULL,
  linked_by VARCHAR(128) NOT NULL,
  linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unlinked_at TIMESTAMPTZ NULL,
  CONSTRAINT ux_incident_case_event UNIQUE(case_id,event_id,relation_type)
);
CREATE INDEX IF NOT EXISTS idx_incident_case_event_event ON incident_case_event(tenant_id,event_id,active);

CREATE TABLE IF NOT EXISTS incident_case_activity (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  activity_type VARCHAR(64) NOT NULL,
  from_status VARCHAR(24) NULL,
  to_status VARCHAR(24) NULL,
  reason_code VARCHAR(64) NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  actor_name VARCHAR(128) NOT NULL,
  trace_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_incident_case_activity_key UNIQUE(tenant_id,case_id,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_incident_case_activity_case ON incident_case_activity(tenant_id,case_id,activity_id);

CREATE TABLE IF NOT EXISTS incident_case_comment (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  visibility VARCHAR(24) NOT NULL DEFAULT 'tenant',
  content TEXT NOT NULL,
  author_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  author_name VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_case_comment_visibility CHECK(visibility IN ('private','participants','tenant'))
);

CREATE TABLE IF NOT EXISTS incident_case_evidence (
  evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  evidence_type VARCHAR(32) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_id VARCHAR(256) NOT NULL,
  object_key TEXT NOT NULL,
  sha256 CHAR(64) NOT NULL,
  media_type VARCHAR(128) NULL,
  masking_policy VARCHAR(128) NULL,
  legal_hold BOOLEAN NOT NULL DEFAULT FALSE,
  purpose VARCHAR(256) NOT NULL,
  added_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_case_evidence_hash UNIQUE(case_id,sha256)
);

CREATE TABLE IF NOT EXISTS incident_case_participant (
  participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  role_type VARCHAR(24) NOT NULL,
  user_id BIGINT NOT NULL REFERENCES sys_user(user_id) ON DELETE RESTRICT,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  removed_at TIMESTAMPTZ NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_case_participant_active ON incident_case_participant(case_id,role_type,user_id) WHERE removed_at IS NULL;

CREATE TABLE IF NOT EXISTS legacy_case_migration_map (
  migration_map_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_table VARCHAR(64) NOT NULL,
  source_id BIGINT NOT NULL,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  target_type VARCHAR(32) NULL,
  target_id BIGINT NULL,
  migration_batch VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL,
  reason TEXT NULL,
  checksum VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_legacy_migration_source UNIQUE(source_table,source_id,migration_batch),
  CONSTRAINT ck_legacy_migration_status CHECK(status IN ('migrated','quarantined','skipped','failed'))
);
