-- Investigation, integration onboarding, data lifecycle, rule, AI and notification governance.

CREATE TABLE IF NOT EXISTS investigation_session (
  investigation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  investigation_no VARCHAR(64) NOT NULL,
  title VARCHAR(256) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  owner_user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  owner_name VARCHAR(128) NOT NULL,
  shared_with_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_investigation_no UNIQUE(tenant_id,investigation_no),
  CONSTRAINT ck_investigation_status CHECK(status IN ('active','completed','archived'))
);

CREATE TABLE IF NOT EXISTS investigation_query_snapshot (
  query_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  investigation_id BIGINT NOT NULL REFERENCES investigation_session(investigation_id) ON DELETE RESTRICT,
  query_type VARCHAR(32) NOT NULL,
  query_json JSONB NOT NULL,
  model_code VARCHAR(128) NULL,
  model_version VARCHAR(128) NULL,
  threshold_policy_version INT NULL,
  data_version VARCHAR(128) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(128) NOT NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_investigation_query_status CHECK(status IN ('queued','running','partial','completed','failed','cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_investigation_query_session ON investigation_query_snapshot(tenant_id,investigation_id,query_id DESC);

CREATE TABLE IF NOT EXISTS investigation_evidence_item (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  investigation_id BIGINT NOT NULL REFERENCES investigation_session(investigation_id) ON DELETE RESTRICT,
  source_type VARCHAR(64) NOT NULL,
  source_id VARCHAR(256) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  note TEXT NULL,
  added_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_investigation_evidence UNIQUE(investigation_id,source_type,source_id)
);

CREATE TABLE IF NOT EXISTS integration_onboarding (
  onboarding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  integration_type VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  current_step INT NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  secret_refs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  capability_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  diagnostics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  config_version INT NOT NULL DEFAULT 1,
  exemption_reason TEXT NULL,
  created_by VARCHAR(128) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_onboarding_step CHECK(current_step BETWEEN 1 AND 7),
  CONSTRAINT ck_onboarding_status CHECK(status IN ('draft','testing','ready','enabled','failed','disabled'))
);

CREATE TABLE IF NOT EXISTS integration_onboarding_activity (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onboarding_id BIGINT NOT NULL REFERENCES integration_onboarding(onboarding_id) ON DELETE RESTRICT,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  step INT NOT NULL,
  action VARCHAR(64) NOT NULL,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_onboarding_activity_step CHECK(step BETWEEN 1 AND 7)
);

CREATE TABLE IF NOT EXISTS integration_onboarding_version (
  onboarding_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onboarding_id BIGINT NOT NULL REFERENCES integration_onboarding(onboarding_id) ON DELETE RESTRICT,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  version INT NOT NULL,
  current_step INT NOT NULL,
  status VARCHAR(24) NOT NULL,
  config_json JSONB NOT NULL,
  secret_refs_json JSONB NOT NULL,
  capability_json JSONB NOT NULL,
  diagnostics_json JSONB NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_onboarding_version UNIQUE(onboarding_id,version)
);

CREATE TABLE IF NOT EXISTS data_retention_policy (
  policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  data_type VARCHAR(64) NOT NULL,
  online_days INT NOT NULL,
  archive_days INT NOT NULL,
  backup_days INT NOT NULL,
  delete_mode VARCHAR(32) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  updated_by VARCHAR(128) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_retention_policy_version UNIQUE(tenant_id,data_type,version),
  CONSTRAINT ck_retention_days CHECK(online_days >= 0 AND archive_days >= online_days AND backup_days >= 0),
  CONSTRAINT ck_retention_status CHECK(status IN ('draft','active','superseded'))
);

CREATE TABLE IF NOT EXISTS data_cleanup_job (
  cleanup_job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  policy_id BIGINT NOT NULL REFERENCES data_retention_policy(policy_id) ON DELETE RESTRICT,
  dry_run BOOLEAN NOT NULL DEFAULT TRUE,
  batch_limit INT NOT NULL DEFAULT 500,
  checkpoint VARCHAR(512) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  scanned_count BIGINT NOT NULL DEFAULT 0,
  affected_count BIGINT NOT NULL DEFAULT 0,
  skipped_hold_count BIGINT NOT NULL DEFAULT 0,
  failure_count BIGINT NOT NULL DEFAULT 0,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_cleanup_batch CHECK(batch_limit BETWEEN 1 AND 10000),
  CONSTRAINT ck_cleanup_status CHECK(status IN ('queued','running','completed','failed','cancelled'))
);

CREATE TABLE IF NOT EXISTS legal_hold (
  legal_hold_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  hold_no VARCHAR(64) NOT NULL,
  object_type VARCHAR(64) NOT NULL,
  object_id VARCHAR(256) NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  reviewed_by VARCHAR(128) NOT NULL,
  released_by VARCHAR(128) NULL,
  released_reason TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at TIMESTAMPTZ NULL,
  CONSTRAINT ux_legal_hold_no UNIQUE(tenant_id,hold_no),
  CONSTRAINT ck_legal_hold_status CHECK(status IN ('active','released'))
);
CREATE INDEX IF NOT EXISTS idx_legal_hold_object ON legal_hold(tenant_id,object_type,object_id,status);

CREATE TABLE IF NOT EXISTS data_processing_register (
  register_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  data_category VARCHAR(64) NOT NULL,
  purpose VARCHAR(256) NOT NULL,
  legal_basis VARCHAR(256) NOT NULL,
  source VARCHAR(256) NOT NULL,
  owner VARCHAR(128) NOT NULL,
  regions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  recipients_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  retention_days INT NOT NULL,
  deletion_method VARCHAR(128) NOT NULL,
  evaluation_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  training_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  version INT NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_processing_retention CHECK(retention_days >= 0),
  CONSTRAINT ck_processing_register_status CHECK(status IN ('draft','approved','retired'))
);

CREATE TABLE IF NOT EXISTS data_deletion_request (
  deletion_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  request_no VARCHAR(64) NOT NULL,
  subject_type VARCHAR(64) NOT NULL,
  subject_ref VARCHAR(256) NOT NULL,
  reason TEXT NOT NULL,
  scope_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'reviewing',
  hold_block_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  requested_by VARCHAR(128) NOT NULL,
  reviewed_by VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ NULL,
  CONSTRAINT ux_deletion_request_no UNIQUE(tenant_id,request_no),
  CONSTRAINT ck_deletion_request_status CHECK(status IN ('reviewing','approved','blocked','running','completed','rejected'))
);

CREATE TABLE IF NOT EXISTS data_deletion_proof (
  deletion_proof_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deletion_request_id BIGINT NOT NULL REFERENCES data_deletion_request(deletion_request_id) ON DELETE RESTRICT,
  store_type VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL,
  object_count BIGINT NOT NULL DEFAULT 0,
  completed_at TIMESTAMPTZ NULL,
  expires_at TIMESTAMPTZ NULL,
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ux_deletion_proof_store UNIQUE(deletion_request_id,store_type)
);

CREATE TABLE IF NOT EXISTS automation_rule (
  rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  rule_code VARCHAR(128) NOT NULL,
  name VARCHAR(256) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  active_version INT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_automation_rule_code UNIQUE(tenant_id,rule_code),
  CONSTRAINT ck_automation_rule_status CHECK(status IN ('draft','pending_approval','canary','published','paused','archived'))
);

CREATE TABLE IF NOT EXISTS automation_rule_version (
  rule_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  rule_id BIGINT NOT NULL REFERENCES automation_rule(rule_id) ON DELETE RESTRICT,
  version INT NOT NULL,
  schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
  condition_json JSONB NOT NULL,
  action_json JSONB NOT NULL,
  noise_control_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  rollout_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  dry_run_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by VARCHAR(128) NOT NULL,
  approved_by VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_automation_rule_version UNIQUE(rule_id,version)
);

CREATE TABLE IF NOT EXISTS automation_rule_execution (
  execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  rule_version_id BIGINT NOT NULL REFERENCES automation_rule_version(rule_version_id) ON DELETE RESTRICT,
  mode VARCHAR(16) NOT NULL,
  input_ref VARCHAR(256) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  matched BOOLEAN NOT NULL,
  explanation_json JSONB NOT NULL,
  action_result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_rule_execution_key UNIQUE(tenant_id,rule_version_id,idempotency_key),
  CONSTRAINT ck_rule_execution_mode CHECK(mode IN ('dry_run','shadow','canary','active'))
);

CREATE TABLE IF NOT EXISTS ai_model_release (
  model_release_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  provider VARCHAR(128) NOT NULL,
  model_code VARCHAR(128) NOT NULL,
  model_version VARCHAR(128) NOT NULL,
  purpose VARCHAR(256) NOT NULL,
  vector_dimension INT NULL,
  runtime VARCHAR(128) NOT NULL,
  owner VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  rollout_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  rollback_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_by VARCHAR(128) NULL,
  released_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_ai_model_release UNIQUE(tenant_id,model_code,model_version),
  CONSTRAINT ck_ai_model_dimension CHECK(vector_dimension IS NULL OR vector_dimension > 0),
  CONSTRAINT ck_ai_model_release_status CHECK(status IN ('draft','evaluating','approved','canary','production','deprecated','rolled_back'))
);

CREATE TABLE IF NOT EXISTS ai_dataset_version (
  dataset_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  dataset_code VARCHAR(128) NOT NULL,
  version VARCHAR(64) NOT NULL,
  source_json JSONB NOT NULL,
  authorization_json JSONB NOT NULL,
  sampling_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  annotation_quality_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  sensitivity VARCHAR(32) NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_ai_dataset_version UNIQUE(tenant_id,dataset_code,version)
);

CREATE TABLE IF NOT EXISTS ai_evaluation_run (
  evaluation_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  model_release_id BIGINT NOT NULL REFERENCES ai_model_release(model_release_id) ON DELETE RESTRICT,
  dataset_version_id BIGINT NOT NULL REFERENCES ai_dataset_version(dataset_version_id) ON DELETE RESTRICT,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  parameters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  environment_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  artifact_uri TEXT NULL,
  conclusion VARCHAR(32) NULL,
  created_by VARCHAR(128) NOT NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_ai_evaluation_status CHECK(status IN ('queued','running','passed','failed','cancelled'))
);

CREATE TABLE IF NOT EXISTS ai_evaluation_item (
  evaluation_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluation_run_id BIGINT NOT NULL REFERENCES ai_evaluation_run(evaluation_run_id) ON DELETE RESTRICT,
  query_ref VARCHAR(256) NOT NULL,
  expected_json JSONB NOT NULL,
  actual_json JSONB NOT NULL,
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_category VARCHAR(64) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_human_feedback (
  feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  object_type VARCHAR(32) NOT NULL,
  object_id VARCHAR(128) NOT NULL,
  model_release_id BIGINT NULL REFERENCES ai_model_release(model_release_id) ON DELETE SET NULL,
  feedback_type VARCHAR(32) NOT NULL,
  reason_code VARCHAR(64) NOT NULL,
  note TEXT NULL,
  review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  usage_scope VARCHAR(32) NOT NULL DEFAULT 'tenant_evaluation',
  submitted_by VARCHAR(128) NOT NULL,
  reviewed_by VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMPTZ NULL,
  CONSTRAINT ck_ai_feedback_review CHECK(review_status IN ('pending','accepted','rejected')),
  CONSTRAINT ck_ai_feedback_scope CHECK(usage_scope IN ('tenant_evaluation','tenant_training','cross_tenant_prohibited'))
);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_review ON ai_human_feedback(tenant_id,review_status,created_at DESC);

CREATE TABLE IF NOT EXISTS ai_threshold_policy (
  threshold_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  scene_code VARCHAR(128) NOT NULL,
  model_release_id BIGINT NOT NULL REFERENCES ai_model_release(model_release_id) ON DELETE RESTRICT,
  version INT NOT NULL,
  threshold_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  approved_by VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_ai_threshold_policy UNIQUE(tenant_id,scene_code,model_release_id,version)
);

CREATE TABLE IF NOT EXISTS ai_drift_snapshot (
  drift_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  model_release_id BIGINT NOT NULL REFERENCES ai_model_release(model_release_id) ON DELETE RESTRICT,
  window_start TIMESTAMPTZ NOT NULL,
  window_end TIMESTAMPTZ NOT NULL,
  metrics_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'normal',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_ai_drift_window UNIQUE(tenant_id,model_release_id,window_start,window_end)
);

CREATE TABLE IF NOT EXISTS notification_template (
  template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  template_code VARCHAR(128) NOT NULL,
  version INT NOT NULL,
  channel VARCHAR(32) NOT NULL,
  content_template TEXT NOT NULL,
  masking_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_notification_template UNIQUE(tenant_id,template_code,version,channel)
);

CREATE TABLE IF NOT EXISTS notification_delivery (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  event_id BIGINT NULL REFERENCES business_event(event_id) ON DELETE RESTRICT,
  channel VARCHAR(32) NOT NULL,
  template_code VARCHAR(128) NOT NULL,
  template_version INT NOT NULL,
  recipient_ref VARCHAR(256) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  attempt_count INT NOT NULL DEFAULT 0,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  next_attempt_at TIMESTAMPTZ NULL,
  delivered_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_notification_idempotency UNIQUE(tenant_id,channel,idempotency_key),
  CONSTRAINT ck_notification_status CHECK(status IN ('queued','sending','delivered','failed','suppressed','escalated','recovered'))
);
