-- SLO operations, enterprise identity, evidence delivery, adapter certification and metering.

CREATE TABLE IF NOT EXISTS slo_policy (
  slo_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_profile_id BIGINT NOT NULL REFERENCES service_profile(profile_id) ON DELETE RESTRICT,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  metric_code VARCHAR(128) NOT NULL,
  target NUMERIC(16,8) NOT NULL,
  comparison VARCHAR(8) NOT NULL,
  window_seconds BIGINT NOT NULL,
  warning_percent INT NOT NULL DEFAULT 50,
  tighten_percent INT NOT NULL DEFAULT 75,
  freeze_percent INT NOT NULL DEFAULT 100,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  effective_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_slo_policy UNIQUE(service_profile_id,tenant_id,metric_code,effective_at),
  CONSTRAINT ck_slo_comparison CHECK(comparison IN ('gte','lte')),
  CONSTRAINT ck_slo_window CHECK(window_seconds > 0),
  CONSTRAINT ck_slo_budget_thresholds CHECK(warning_percent BETWEEN 1 AND tighten_percent AND tighten_percent <= freeze_percent)
);

CREATE TABLE IF NOT EXISTS slo_snapshot (
  slo_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slo_policy_id BIGINT NOT NULL REFERENCES slo_policy(slo_policy_id) ON DELETE RESTRICT,
  window_start TIMESTAMPTZ NOT NULL,
  window_end TIMESTAMPTZ NOT NULL,
  numerator NUMERIC(24,8) NOT NULL,
  denominator NUMERIC(24,8) NOT NULL,
  value NUMERIC(20,10) NULL,
  error_budget_consumed_percent NUMERIC(12,4) NULL,
  status VARCHAR(24) NOT NULL,
  dimensions_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_slo_snapshot UNIQUE(slo_policy_id,window_start,window_end),
  CONSTRAINT ck_slo_denominator CHECK(denominator >= 0),
  CONSTRAINT ck_slo_snapshot_status CHECK(status IN ('healthy','warning','tightened','frozen','insufficient_data'))
);

CREATE TABLE IF NOT EXISTS maintenance_window (
  maintenance_window_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  title VARCHAR(256) NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  impact_json JSONB NOT NULL,
  approved_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_maintenance_window_time CHECK(ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS platform_change_record (
  change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  change_type VARCHAR(32) NOT NULL,
  version_ref VARCHAR(128) NOT NULL,
  summary VARCHAR(512) NOT NULL,
  diff_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  changed_by VARCHAR(128) NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_platform_change_time ON platform_change_record(changed_at DESC,change_id DESC);

CREATE TABLE IF NOT EXISTS oidc_provider_config (
  oidc_provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  provider_code VARCHAR(64) NOT NULL,
  authority TEXT NOT NULL,
  client_id VARCHAR(256) NOT NULL,
  client_secret_ref VARCHAR(512) NULL,
  redirect_uri TEXT NOT NULL,
  scopes_json JSONB NOT NULL DEFAULT '["openid","profile"]'::jsonb,
  require_pkce BOOLEAN NOT NULL DEFAULT TRUE,
  require_mfa BOOLEAN NOT NULL DEFAULT TRUE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  version INT NOT NULL DEFAULT 1,
  updated_by VARCHAR(128) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_oidc_provider UNIQUE(tenant_id,provider_code,version)
);

CREATE TABLE IF NOT EXISTS identity_group_mapping (
  mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oidc_provider_id BIGINT NOT NULL REFERENCES oidc_provider_config(oidc_provider_id) ON DELETE RESTRICT,
  external_group VARCHAR(256) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  approved_by VARCHAR(128) NULL,
  version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_identity_group_mapping UNIQUE(oidc_provider_id,external_group,tenant_id,version)
);

CREATE TABLE IF NOT EXISTS auth_session (
  session_id UUID PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  user_id BIGINT NULL REFERENCES sys_user(user_id) ON DELETE SET NULL,
  user_name VARCHAR(128) NOT NULL,
  provider_code VARCHAR(64) NOT NULL,
  authentication_method VARCHAR(32) NOT NULL,
  authentication_strength VARCHAR(64) NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ NULL,
  revoked_by VARCHAR(128) NULL,
  revoke_reason VARCHAR(512) NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ck_auth_session_time CHECK(expires_at > issued_at)
);
CREATE INDEX IF NOT EXISTS idx_auth_session_user_active ON auth_session(user_name,expires_at DESC) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS step_up_challenge (
  challenge_id UUID PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES auth_session(session_id) ON DELETE RESTRICT,
  action VARCHAR(128) NOT NULL,
  resource_ref VARCHAR(256) NULL,
  required_strength VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  expires_at TIMESTAMPTZ NOT NULL,
  verified_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_step_up_status CHECK(status IN ('pending','verified','expired','failed'))
);

CREATE TABLE IF NOT EXISTS break_glass_account (
  break_glass_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES sys_user(user_id) ON DELETE RESTRICT,
  credential_custodian VARCHAR(256) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  last_exercised_at TIMESTAMPTZ NULL,
  last_rotated_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_break_glass_user UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS evidence_export (
  evidence_export_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  purpose VARCHAR(256) NOT NULL,
  masking_policy VARCHAR(128) NOT NULL,
  manifest_json JSONB NOT NULL,
  manifest_sha256 CHAR(64) NOT NULL,
  artifact_key TEXT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'generating',
  requested_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ck_evidence_export_status CHECK(status IN ('generating','ready','failed','expired','revoked'))
);

CREATE TABLE IF NOT EXISTS evidence_access_grant (
  grant_id UUID PRIMARY KEY,
  evidence_export_id BIGINT NOT NULL REFERENCES evidence_export(evidence_export_id) ON DELETE RESTRICT,
  grantee VARCHAR(256) NOT NULL,
  purpose VARCHAR(256) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ NULL,
  download_count INT NOT NULL DEFAULT 0,
  max_downloads INT NOT NULL DEFAULT 1,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_evidence_download_count CHECK(download_count >= 0 AND max_downloads > 0)
);

CREATE TABLE IF NOT EXISTS adapter_manifest (
  adapter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adapter_code VARCHAR(128) NOT NULL,
  version VARCHAR(64) NOT NULL,
  protocol VARCHAR(64) NOT NULL,
  lifecycle_status VARCHAR(24) NOT NULL DEFAULT 'experimental',
  manifest_json JSONB NOT NULL,
  config_schema_json JSONB NOT NULL,
  security_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  package_digest VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_adapter_manifest UNIQUE(adapter_code,version),
  CONSTRAINT ck_adapter_lifecycle CHECK(lifecycle_status IN ('experimental','certified','deprecated','unsupported'))
);

CREATE TABLE IF NOT EXISTS adapter_certification (
  certification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adapter_id BIGINT NOT NULL REFERENCES adapter_manifest(adapter_id) ON DELETE RESTRICT,
  device_model VARCHAR(128) NOT NULL,
  firmware_version VARCHAR(128) NOT NULL,
  capabilities_json JSONB NOT NULL,
  limitations_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_uri TEXT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'experimental',
  tested_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ux_adapter_certification UNIQUE(adapter_id,device_model,firmware_version),
  CONSTRAINT ck_adapter_certification_status CHECK(status IN ('experimental','certified','failed','expired'))
);

CREATE TABLE IF NOT EXISTS tenant_entitlement (
  entitlement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  entitlement_code VARCHAR(128) NOT NULL,
  modules_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  limits_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  support_level VARCHAR(32) NOT NULL,
  valid_from TIMESTAMPTZ NOT NULL,
  valid_to TIMESTAMPTZ NOT NULL,
  grace_until TIMESTAMPTZ NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  signature VARCHAR(512) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_tenant_entitlement UNIQUE(tenant_id,entitlement_code,valid_from),
  CONSTRAINT ck_entitlement_time CHECK(valid_to > valid_from),
  CONSTRAINT ck_entitlement_status CHECK(status IN ('active','grace','restricted','expired','revoked'))
);

CREATE TABLE IF NOT EXISTS tenant_quota_policy (
  quota_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  metric_code VARCHAR(128) NOT NULL,
  limit_value NUMERIC(20,4) NOT NULL,
  enforcement VARCHAR(16) NOT NULL,
  warning_percent INT NOT NULL DEFAULT 80,
  valid_from TIMESTAMPTZ NOT NULL,
  valid_to TIMESTAMPTZ NULL,
  approved_by VARCHAR(128) NOT NULL,
  CONSTRAINT ck_quota_limit CHECK(limit_value >= 0),
  CONSTRAINT ck_quota_enforcement CHECK(enforcement IN ('soft','hard')),
  CONSTRAINT ck_quota_warning CHECK(warning_percent BETWEEN 1 AND 100)
);

CREATE TABLE IF NOT EXISTS tenant_usage_ledger (
  usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  project_ref VARCHAR(128) NULL,
  provider_ref VARCHAR(128) NULL,
  pipeline_ref VARCHAR(128) NULL,
  metric_code VARCHAR(128) NOT NULL,
  quantity NUMERIC(20,6) NOT NULL,
  unit VARCHAR(32) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  adjustment_of BIGINT NULL REFERENCES tenant_usage_ledger(usage_id) ON DELETE RESTRICT,
  adjustment_reason VARCHAR(512) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_usage_idempotency UNIQUE(tenant_id,metric_code,idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_usage_tenant_metric_time ON tenant_usage_ledger(tenant_id,metric_code,occurred_at DESC);

CREATE TABLE IF NOT EXISTS tenant_cost_ledger (
  cost_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  usage_id BIGINT NULL REFERENCES tenant_usage_ledger(usage_id) ON DELETE RESTRICT,
  cost_category VARCHAR(64) NOT NULL,
  amount NUMERIC(20,6) NOT NULL,
  currency CHAR(3) NOT NULL,
  calculation_version VARCHAR(64) NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_metric_definition (
  metric_definition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_code VARCHAR(128) NOT NULL,
  version INT NOT NULL,
  name VARCHAR(256) NOT NULL,
  numerator_definition TEXT NULL,
  denominator_definition TEXT NULL,
  window_definition VARCHAR(128) NOT NULL,
  effective_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ux_product_metric_definition UNIQUE(metric_code,version)
);

CREATE TABLE IF NOT EXISTS product_metric_snapshot (
  metric_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  metric_definition_id BIGINT NOT NULL REFERENCES product_metric_definition(metric_definition_id) ON DELETE RESTRICT,
  window_start TIMESTAMPTZ NOT NULL,
  window_end TIMESTAMPTZ NOT NULL,
  numerator NUMERIC(24,8) NULL,
  denominator NUMERIC(24,8) NULL,
  value NUMERIC(24,8) NULL,
  dimensions_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_product_metric_snapshot UNIQUE(tenant_id,metric_definition_id,window_start,window_end)
);

CREATE TABLE IF NOT EXISTS controlled_query_plan (
  query_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  investigation_id BIGINT NULL REFERENCES investigation_session(investigation_id) ON DELETE RESTRICT,
  natural_language TEXT NOT NULL,
  plan_json JSONB NOT NULL,
  prompt_template_version VARCHAR(64) NOT NULL,
  model_version VARCHAR(128) NOT NULL,
  permission_scope_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending_confirmation',
  confirmed_by VARCHAR(128) NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_query_plan_status CHECK(status IN ('pending_confirmation','confirmed','executed','rejected'))
);

