-- Immutable archive/tombstone evidence for retention-driven deletion.
CREATE TABLE IF NOT EXISTS data_archive_record (
  archive_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  data_type VARCHAR(64) NOT NULL,
  object_id VARCHAR(256) NOT NULL,
  policy_id BIGINT NOT NULL REFERENCES data_retention_policy(policy_id) ON DELETE RESTRICT,
  snapshot_json JSONB NOT NULL,
  snapshot_sha256 CHAR(64) NOT NULL,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_data_archive_object UNIQUE(tenant_id,data_type,object_id,policy_id)
);

CREATE TABLE IF NOT EXISTS data_deletion_tombstone (
  deletion_tombstone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  cleanup_job_id BIGINT NOT NULL REFERENCES data_cleanup_job(cleanup_job_id) ON DELETE RESTRICT,
  data_type VARCHAR(64) NOT NULL,
  object_id VARCHAR(256) NOT NULL,
  archive_record_id BIGINT NOT NULL REFERENCES data_archive_record(archive_record_id) ON DELETE RESTRICT,
  deletion_event_id BIGINT NULL REFERENCES integration_outbox(outbox_id) ON DELETE SET NULL,
  deleted_by VARCHAR(128) NOT NULL,
  deleted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_data_deletion_job_object UNIQUE(cleanup_job_id,data_type,object_id)
);

CREATE INDEX IF NOT EXISTS idx_data_archive_lookup
  ON data_archive_record(tenant_id,data_type,object_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_data_archive_object_null_safe
  ON data_archive_record(tenant_id,data_type,object_id,policy_id) NULLS NOT DISTINCT;
