-- Controlled legacy alert/workflow migration and case SLA timestamps.
ALTER TABLE incident_case
  ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ NULL;

CREATE TABLE IF NOT EXISTS legacy_migration_run (
  migration_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_batch VARCHAR(128) NOT NULL UNIQUE,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  status VARCHAR(24) NOT NULL DEFAULT 'preflight',
  read_mode VARCHAR(24) NOT NULL DEFAULT 'legacy',
  dry_run BOOLEAN NOT NULL DEFAULT TRUE,
  preflight_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  reconciliation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  checkpoint_alert_id BIGINT NULL,
  migrated_count BIGINT NOT NULL DEFAULT 0,
  quarantined_count BIGINT NOT NULL DEFAULT 0,
  failed_count BIGINT NOT NULL DEFAULT 0,
  shadow_owner VARCHAR(128) NOT NULL,
  shadow_deadline TIMESTAMPTZ NOT NULL,
  cutover_approved_by VARCHAR(128) NULL,
  cutover_at TIMESTAMPTZ NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 1,
  CONSTRAINT ck_legacy_run_status CHECK(status IN ('preflight','blocked','ready','backfilling','shadow','cutover','completed','failed','rolled_back')),
  CONSTRAINT ck_legacy_read_mode CHECK(read_mode IN ('legacy','shadow','authoritative'))
);

CREATE TABLE IF NOT EXISTS api_compat_usage (
  usage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_family VARCHAR(128) NOT NULL,
  method VARCHAR(16) NOT NULL,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE SET NULL,
  actor VARCHAR(128) NULL,
  client_ref VARCHAR(256) NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_api_compat_usage_route_time ON api_compat_usage(route_family,occurred_at DESC);
