CREATE TABLE IF NOT EXISTS release_gate_evidence (
  evidence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gate_run_id BIGINT NOT NULL REFERENCES release_gate_run(gate_run_id) ON DELETE RESTRICT,
  check_code VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL,
  command_line TEXT NULL,
  exit_code INT NULL,
  environment_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  log_summary TEXT NULL,
  artifact_uri TEXT NULL,
  submitted_by VARCHAR(128) NOT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_release_gate_check UNIQUE(gate_run_id,check_code),
  CONSTRAINT ck_release_gate_evidence_status CHECK(status IN ('passed','failed','blocked','not_run'))
);

ALTER TABLE release_gate_run
  ADD COLUMN IF NOT EXISTS report_uri TEXT NULL,
  ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1;
