ALTER TABLE notification_delivery
  ADD COLUMN IF NOT EXISTS payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS provider_ref VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS locked_by VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS lock_until TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS max_attempts INT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS trace_id VARCHAR(128) NULL;

CREATE INDEX IF NOT EXISTS idx_notification_delivery_work
  ON notification_delivery(status,next_attempt_at,lock_until,notification_id);

CREATE TABLE IF NOT EXISTS notification_receipt (
  receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  notification_id BIGINT NOT NULL REFERENCES notification_delivery(notification_id) ON DELETE RESTRICT,
  provider_receipt_id VARCHAR(256) NOT NULL,
  status VARCHAR(24) NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_notification_receipt UNIQUE(tenant_id,provider_receipt_id)
);
