-- Executable rule, AI governance, break-glass, certification, analytics and mobile workflows.

ALTER TABLE automation_rule
  ADD COLUMN IF NOT EXISTS event_limit_per_hour INT NOT NULL DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS tripped_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS trip_reason TEXT NULL;

ALTER TABLE automation_rule
  DROP CONSTRAINT IF EXISTS ck_automation_rule_event_limit;
ALTER TABLE automation_rule
  ADD CONSTRAINT ck_automation_rule_event_limit CHECK(event_limit_per_hour BETWEEN 1 AND 1000000);

ALTER TABLE automation_rule_execution
  ADD COLUMN IF NOT EXISTS match_key VARCHAR(512) NULL,
  ADD COLUMN IF NOT EXISTS action_status VARCHAR(24) NOT NULL DEFAULT 'not_applicable',
  ADD COLUMN IF NOT EXISTS error_message TEXT NULL;

ALTER TABLE automation_rule_execution
  DROP CONSTRAINT IF EXISTS ck_rule_execution_action_status;
ALTER TABLE automation_rule_execution
  ADD CONSTRAINT ck_rule_execution_action_status
  CHECK(action_status IN ('not_applicable','suppressed','shadowed','completed','failed'));

CREATE INDEX IF NOT EXISTS idx_rule_execution_noise_control
  ON automation_rule_execution(tenant_id,rule_version_id,match_key,created_at DESC)
  WHERE matched=TRUE;

CREATE TABLE IF NOT EXISTS automation_rule_cursor (
  cursor_name VARCHAR(64) PRIMARY KEY,
  last_event_id BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO automation_rule_cursor(cursor_name,last_event_id)
VALUES('business_event',0)
ON CONFLICT(cursor_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS break_glass_event (
  break_glass_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  break_glass_account_id BIGINT NOT NULL REFERENCES break_glass_account(break_glass_account_id) ON DELETE RESTRICT,
  user_id BIGINT NOT NULL REFERENCES sys_user(user_id) ON DELETE RESTRICT,
  action VARCHAR(24) NOT NULL,
  outcome VARCHAR(24) NOT NULL,
  reason VARCHAR(512) NOT NULL,
  actor VARCHAR(128) NOT NULL,
  source_ip VARCHAR(64) NULL,
  trace_id VARCHAR(128) NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_break_glass_action CHECK(action IN ('registered','enabled','disabled','exercised','used','rotated')),
  CONSTRAINT ck_break_glass_outcome CHECK(outcome IN ('succeeded','failed','blocked'))
);
CREATE INDEX IF NOT EXISTS idx_break_glass_event_time ON break_glass_event(occurred_at DESC);

ALTER TABLE break_glass_account
  ADD COLUMN IF NOT EXISTS enabled_until TIMESTAMPTZ NULL;

CREATE TABLE IF NOT EXISTS adapter_contract_run (
  contract_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adapter_id BIGINT NOT NULL REFERENCES adapter_manifest(adapter_id) ON DELETE RESTRICT,
  device_model VARCHAR(128) NOT NULL,
  firmware_version VARCHAR(128) NOT NULL,
  environment_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  checks_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL,
  report_uri TEXT NULL,
  executed_by VARCHAR(128) NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_adapter_contract_run_status CHECK(status IN ('passed','failed','blocked'))
);
CREATE INDEX IF NOT EXISTS idx_adapter_contract_run_adapter ON adapter_contract_run(adapter_id,executed_at DESC);

CREATE TABLE IF NOT EXISTS product_analytics_event (
  analytics_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  event_name VARCHAR(128) NOT NULL,
  object_type VARCHAR(64) NULL,
  object_id VARCHAR(128) NULL,
  properties_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor VARCHAR(128) NOT NULL,
  session_ref VARCHAR(128) NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_analytics_tenant_time
  ON product_analytics_event(tenant_id,event_name,occurred_at DESC);

CREATE TABLE IF NOT EXISTS mobile_action_draft (
  mobile_draft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  user_name VARCHAR(128) NOT NULL,
  client_draft_id UUID NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  object_type VARCHAR(64) NOT NULL,
  object_id VARCHAR(128) NULL,
  base_version INT NULL,
  payload_json JSONB NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  conflict_json JSONB NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  synced_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_mobile_action_draft UNIQUE(tenant_id,user_name,client_draft_id),
  CONSTRAINT ck_mobile_action_draft_status CHECK(status IN ('draft','synced','conflict','discarded','expired'))
);
CREATE INDEX IF NOT EXISTS idx_mobile_action_draft_user
  ON mobile_action_draft(tenant_id,user_name,status,updated_at DESC);
