-- Complete the remaining commercial workflows: case collaboration, channel adapters,
-- derived-store deletion proofs, mobile deep links and controlled-query safety evaluation.

CREATE TABLE IF NOT EXISTS incident_case_template (
  template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  template_code VARCHAR(128) NOT NULL,
  version INT NOT NULL DEFAULT 1,
  name VARCHAR(256) NOT NULL,
  event_type VARCHAR(128) NULL,
  default_priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  default_sla_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  checklist_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  created_by VARCHAR(128) NOT NULL,
  approved_by VARCHAR(128) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_case_template_version UNIQUE(tenant_id,template_code,version),
  CONSTRAINT ck_case_template_priority CHECK(default_priority IN ('low','normal','high','urgent')),
  CONSTRAINT ck_case_template_status CHECK(status IN ('draft','active','retired'))
);

CREATE TABLE IF NOT EXISTS incident_case_checklist_item (
  checklist_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  item_code VARCHAR(128) NOT NULL,
  title VARCHAR(256) NOT NULL,
  required BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  completed_by VARCHAR(128) NULL,
  completed_at TIMESTAMPTZ NULL,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_case_checklist_item UNIQUE(case_id,item_code),
  CONSTRAINT ck_case_checklist_status CHECK(status IN ('pending','in_progress','completed','skipped'))
);

CREATE TABLE IF NOT EXISTS incident_case_relation (
  relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  source_case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  target_case_id BIGINT NOT NULL REFERENCES incident_case(case_id) ON DELETE RESTRICT,
  relation_type VARCHAR(24) NOT NULL,
  reason VARCHAR(512) NOT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_case_relation UNIQUE(source_case_id,target_case_id,relation_type),
  CONSTRAINT ck_case_relation_type CHECK(relation_type IN ('merged_into','split_from','related')),
  CONSTRAINT ck_case_relation_not_self CHECK(source_case_id <> target_case_id)
);
CREATE INDEX IF NOT EXISTS idx_case_relation_target ON incident_case_relation(tenant_id,target_case_id,relation_type);

CREATE TABLE IF NOT EXISTS notification_channel_config (
  channel_config_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  channel VARCHAR(32) NOT NULL,
  provider_code VARCHAR(128) NOT NULL,
  endpoint_uri TEXT NULL,
  secret_ref VARCHAR(512) NULL,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  version INT NOT NULL DEFAULT 1,
  created_by VARCHAR(128) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_notification_channel_config UNIQUE(tenant_id,channel,provider_code,version),
  CONSTRAINT ck_notification_channel_config_channel CHECK(channel IN ('email','sms','collaboration','ticket','webhook','in_app')),
  CONSTRAINT ck_notification_channel_config_status CHECK(status IN ('draft','active','disabled'))
);
CREATE INDEX IF NOT EXISTS idx_notification_channel_lookup
  ON notification_channel_config(tenant_id,channel,status,version DESC);

CREATE TABLE IF NOT EXISTS data_deletion_delivery (
  delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deletion_tombstone_id BIGINT NOT NULL REFERENCES data_deletion_tombstone(deletion_tombstone_id) ON DELETE RESTRICT,
  store_type VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_by VARCHAR(128) NULL,
  lease_until TIMESTAMPTZ NULL,
  last_error TEXT NULL,
  proof_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  completed_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_data_deletion_delivery UNIQUE(deletion_tombstone_id,store_type),
  CONSTRAINT ck_data_deletion_delivery_store CHECK(store_type IN ('postgres','pgvector','arangodb','redis','object_storage','exports','backup')),
  CONSTRAINT ck_data_deletion_delivery_status CHECK(status IN ('pending','running','completed','failed','blocked'))
);
CREATE INDEX IF NOT EXISTS idx_data_deletion_delivery_work
  ON data_deletion_delivery(status,available_at,lease_until,delivery_id);

CREATE TABLE IF NOT EXISTS mobile_push_subscription (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  user_name VARCHAR(128) NOT NULL,
  endpoint_uri TEXT NOT NULL,
  key_p256dh TEXT NOT NULL,
  key_auth TEXT NOT NULL,
  user_agent VARCHAR(512) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_mobile_push_subscription UNIQUE(tenant_id,user_name,endpoint_uri),
  CONSTRAINT ck_mobile_push_subscription_status CHECK(status IN ('active','revoked'))
);

ALTER TABLE incident_case_evidence
  ADD COLUMN IF NOT EXISTS detail_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS controlled_query_safety_evaluation (
  evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NULL REFERENCES tenant_project(tenant_id) ON DELETE RESTRICT,
  suite_version VARCHAR(64) NOT NULL,
  query_count INT NOT NULL,
  blocked_count INT NOT NULL DEFAULT 0,
  cross_tenant_blocked_count INT NOT NULL DEFAULT 0,
  raw_media_blocked_count INT NOT NULL DEFAULT 0,
  injection_blocked_count INT NOT NULL DEFAULT 0,
  artifact_uri TEXT NULL,
  status VARCHAR(24) NOT NULL,
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  executed_by VARCHAR(128) NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_controlled_query_safety_status CHECK(status IN ('passed','failed','blocked')),
  CONSTRAINT ck_controlled_query_safety_counts CHECK(query_count >= 0 AND blocked_count >= 0)
);

INSERT INTO product_metric_definition(
  metric_code,version,name,numerator_definition,denominator_definition,window_definition,effective_at)
VALUES
  ('case_sla_compliance',1,'Case SLA compliance','Cases closed on or before resolve_due_at','Closed cases with resolve_due_at','Requested dashboard window','2026-07-23T00:00:00Z'),
  ('case_evidence_completeness',1,'Closed case evidence completeness','Closed cases with at least one evidence item','Closed cases','Requested dashboard window','2026-07-23T00:00:00Z'),
  ('case_reopen_rate',1,'Case reopen rate','Distinct cases with a reopened activity','Cases closed or resolved','Requested dashboard window','2026-07-23T00:00:00Z'),
  ('feedback_false_positive_rate',1,'False-positive feedback rate','False-positive feedback items','All human feedback items','Requested dashboard window','2026-07-23T00:00:00Z'),
  ('provider_job_success_rate',1,'Provider job success rate','Completed media-analysis jobs','Terminal media-analysis jobs','Requested dashboard window','2026-07-23T00:00:00Z')
ON CONFLICT(metric_code,version) DO NOTHING;
